/-
Copyright (c) 2026 acorn contributors. All rights reserved.
Released under the MIT license as described in the repository LICENSE.
Authors: acorn contributors
-/
import AcornTools.ModuleInventory
import AcornTools.OwnershipSource

/-! # Ordinary Lean verification

The complete suite in `scripts/verify.sh` invokes this tool after shell and Git
whitespace checks. It uses the provisioned Lean/Lake/native tools.
-/
namespace AcornGate

/-- A failed subprocess stops admission; successful output remains ordinary console output. -/
def run (cmd : String) (args : Array String := #[]) (cwd : Option System.FilePath := none) : IO Unit := do
  let started ← IO.monoMsNow
  let child ← IO.Process.spawn { cmd, args, cwd, stdin := .null }
  let status ← child.wait
  IO.println s!"check {cmd}: {(← IO.monoMsNow) - started} ms; status {status}"
  (← IO.getStdout).flush
  unless status == 0 do throw (IO.userError s!"{cmd} {args} exited {status}")

/-- Every build goes through the same local-dependency admission. -/
def lake (args : Array String) : IO Unit :=
  run "lean" (#["-DwarningAsError=true", "-DautoImplicit=false", "--run", "Bootstrap.lean"] ++ args)

/-- Verify a generated resource as complete bytes, never as a sampled semantic claim. -/
def browserKernel : IO Unit := do
  let child ← IO.Process.spawn {
    cmd := ".lake/build/bin/browser-kernel",
    stdin := .null, stdout := .piped, stderr := .inherit }
  let generated ← child.stdout.readBinToEnd
  let status ← child.wait
  unless status == 0 && generated == (← IO.FS.readBinFile "../viewer/static/browser-kernel.js") do
    throw (IO.userError "browser kernel differs from its Lean-owned emitter")
  IO.println "browser kernel: complete generated bytes match"

/-- The three fixed mutation arms are independent. Reap every task before
reporting any failure, so a refused arm cannot leave another audit running. -/
def audits : IO Unit := do
  let tasks ← [#["audit"], #["audit", "--explore-rate", "annealed"],
      #["audit", "--arm", "differential"]].mapM fun args =>
    IO.asTask (run "lean/.lake/build/bin/acorn-core" args (some ".."))
  let mut failures := []
  for task in tasks do
    match task.get with
    | .ok () => pure ()
    | .error error => failures := error.toString :: failures
  unless failures.isEmpty do
    throw (IO.userError (String.intercalate "\n" failures.reverse))

/-- Source admission precedes application compilation; every discovered module is built.
Every declared native entry retains compilation and execution-route admission. -/
def verify : IO Unit := do
  lake #["build", "lean-boundary-audit"]
  discard AcornOwnershipAudit.sources
  discard AcornOwnershipAudit.targets
  IO.println "ownership: source modules and Lake entries admitted"
  run ".lake/build/bin/lean-boundary-audit" #["source"]
  run ".lake/build/bin/lean-boundary-audit" #["proof-source"]
  let modules ← AcornModuleInventory.allModules
  let moduleTargets := modules.map fun name => "+" ++ name.toString
  let nativeTargets := (modules.filter AcornModuleInventory.nativeModule).map
    fun name => "+" ++ name.toString ++ ":c.o.export"
  let executableTargets := AcornOwnership.executables.map (·.1)
  -- Lake fetches targets in order and can wait for imports while doing so.
  -- Request native work first so C compilation/linking can overlap proof builds.
  lake (#["build"] ++ executableTargets ++ nativeTargets ++ moduleTargets)
  run ".lake/build/bin/lean-boundary-audit" #["compiled"]
  run ".lake/build/bin/native-audit"
  browserKernel
  run ".lake/build/bin/ownership-audit" #["complete"]
  IO.println "All required Lean checks passed, including proof, execution and corpus admission."

end AcornGate

/-- Failures never trigger provisioning or fall back to another implementation. -/
def main (args : List String) : IO UInt32 := do
  try
    match args with
    | [] => AcornGate.verify
    | ["diagnostics"] =>
      AcornGate.lake #["build", "acorn-core"]
      AcornGate.audits
      IO.println "Optional mutation diagnostics passed; this is not ordinary merge verification."
    | _ => throw (IO.userError "usage: acorn-gates [diagnostics]")
    return 0
  catch error =>
    IO.eprintln s!"acorn-gates: {error}"
    return 1
