/-
Copyright (c) 2026 acorn contributors. All rights reserved.
Released under the MIT license as described in the repository LICENSE.
Authors: acorn contributors
-/
import AcornTools.ModuleInventory
import AcornTools.OwnershipSource

/-! # Ordinary Lean verification

The complete suite in `scripts/verify.sh` invokes this tool after shell and Git
whitespace checks. It uses the provisioned Lean/Lake/native tools.
-/
namespace AcornGate

/-- A failed subprocess stops admission; successful output remains ordinary console output. -/
def run (cmd : String) (args : Array String := #[]) (cwd : Option System.FilePath := none)
    (env : Array (String × Option String) := #[]) : IO Unit := do
  let started ← IO.monoMsNow
  let child ← IO.Process.spawn { cmd, args, cwd, env, stdin := .null }
  let status ← child.wait
  IO.println s!"check {cmd}: {(← IO.monoMsNow) - started} ms; status {status}"
  (← IO.getStdout).flush
  unless status == 0 do throw (IO.userError s!"{cmd} {args} exited {status}")

/-- Every build goes through the same local-dependency admission. -/
def lake (args : Array String) : IO Unit :=
  run "lean" (#["-DwarningAsError=true", "-DautoImplicit=false", "--run", "Bootstrap.lean"] ++ args)

/-- Verify a generated resource as complete bytes, never as a sampled semantic claim. -/
def browserKernel : IO Unit := do
  let child ← IO.Process.spawn {
    cmd := ".lake/build/bin/browser-kernel",
    stdin := .null, stdout := .piped, stderr := .inherit }
  let generated ← child.stdout.readBinToEnd
  let status ← child.wait
  unless status == 0 && generated == (← IO.FS.readBinFile "../viewer/static/browser-kernel.js") do
    throw (IO.userError "browser kernel differs from its Lean-owned emitter")
  IO.println "browser kernel: complete generated bytes match"

/-- The three fixed mutation arms are independent. Reap every task before
reporting any failure, so a refused arm cannot leave another audit running. -/
def audits : IO Unit := do
  let tasks ← [#["audit"], #["audit", "--explore-rate", "annealed"],
      #["audit", "--arm", "differential"]].mapM fun args =>
    IO.asTask (run "lean/.lake/build/bin/acorn-core" args (some ".."))
  let mut failures := []
  for task in tasks do
    match task.get with
    | .ok () => pure ()
    | .error error => failures := error.toString :: failures
  unless failures.isEmpty do
    throw (IO.userError (String.intercalate "\n" failures.reverse))

/-- The refusal for a documentation dependency that is not provisioned. -/
def siteUnprovisioned (missing : String) : IO.Error := IO.userError
  s!"missing pinned documentation dependencies ({missing}); run (cd site && lake build verso/VersoManual)"

/-- The documentation site in `site/` is a second Lake workspace over this package's
dependency checkouts and pinned Verso. Each locked Git dependency is mapped to its
provisioned checkout, as the bootstrap does for this workspace, so Lake fetches
nothing here. A missing checkout is refused. -/
def siteOverrides : IO String := do
  let lock ← IO.ofExcept (Lean.Json.parse (← IO.FS.readFile "../site/lake-manifest.json"))
  let mut entries : Array Lean.Json := #[]
  for entry in ← IO.ofExcept (lock.getObjValAs? (Array Lean.Json) "packages") do
    unless (← IO.ofExcept (entry.getObjValAs? String "type")) == "git" do continue
    let name ← IO.ofExcept (entry.getObjValAs? String "name")
    let config ← IO.ofExcept (entry.getObjValAs? String "configFile")
    for component in [name, config] do
      unless !component.isEmpty && component != "." && component != ".." &&
          component.toList.all (fun c => c.isAlphanum || c == '-' || c == '_' || c == '.') do
        throw (IO.userError s!"unsupported documentation package component: {component}")
    let dir := s!"../lean/.lake/packages/{name}"
    unless ← (System.FilePath.mk ".lake/packages" / name / config).pathExists do
      throw (siteUnprovisioned name)
    entries := entries.push (Lean.Json.mkObj [
      ("name", name), ("scope", ← IO.ofExcept (entry.getObjVal? "scope")),
      ("inherited", ← IO.ofExcept (entry.getObjVal? "inherited")), ("configFile", config),
      ("manifestFile", ← IO.ofExcept (entry.getObjVal? "manifestFile")),
      ("type", "path"), ("dir", dir)])
  IO.FS.createDirAll "../site/.lake"
  IO.FS.writeFile "../site/.lake/acorn-path-packages.json"
    ((Lean.Json.mkObj [("version", "1.2.0"), ("packages", Lean.toJson entries)]).compress ++ "\n")
  return ".lake/acorn-path-packages.json"

/-- Build the documents, which elaborates every reference they make to a Lean owner, then
render them: each kept Markdown file must equal the rendering of its document, or with
`write` is written from it. Verso is a provisioned dependency. Lake itself decides its
readiness: with `--no-build` it exits 3 unless every artifact of `VersoManual` is current,
so verification never compiles a dependency inside its deadline. The renderer runs
interpreted; a linked executable would compile the native code of every proof module a
document imports. -/
def site (write : Bool) : IO Unit := do
  let flags := #["--no-cache", "--wfail", s!"--packages={← siteOverrides}"]
  let env := #[("LAKE_ARTIFACT_CACHE", some "false")]
  let ready ← IO.Process.output {
    cmd := "lake", args := flags ++ #["build", "--no-build", "verso/VersoManual"],
    cwd := some "../site", stdin := .null, env }
  if ready.exitCode == 3 then throw (siteUnprovisioned "Verso is not built")
  unless ready.exitCode == 0 do
    throw (IO.userError s!"Lake could not decide Verso provisioning:\n{ready.stdout}{ready.stderr}")
  run "lake" (flags ++ #["build", "AcornSite", "AcornDocs"]) (some "../site") env
  run "lake" (flags ++ #["env", "lean", "-DwarningAsError=true", "-DautoImplicit=false", "--run",
    "Main.lean"] ++ (if write then #["write"] else #[])) (some "../site") env
  IO.println "site: documents elaborated against their Lean owners; kept Markdown matches"

/-- Source admission precedes application compilation; every discovered module is built.
Every declared native entry retains compilation and execution-route admission. -/
def verify : IO Unit := do
  lake #["build", "lean-boundary-audit"]
  discard AcornOwnershipAudit.sources
  discard AcornOwnershipAudit.targets
  IO.println "ownership: source modules and Lake entries admitted"
  run ".lake/build/bin/lean-boundary-audit" #["source"]
  run ".lake/build/bin/lean-boundary-audit" #["proof-source"]
  let modules ← AcornModuleInventory.allModules
  let moduleTargets := modules.map fun name => "+" ++ name.toString
  let nativeTargets := (modules.filter AcornModuleInventory.nativeModule).map
    fun name => "+" ++ name.toString ++ ":c.o.export"
  let executableTargets := AcornOwnership.executables.map (·.1)
  -- Lake fetches targets in order and can wait for imports while doing so.
  -- Request native work first so C compilation/linking can overlap proof builds.
  lake (#["build"] ++ executableTargets ++ nativeTargets ++ moduleTargets)
  run ".lake/build/bin/lean-boundary-audit" #["compiled"]
  run ".lake/build/bin/native-audit"
  browserKernel
  run ".lake/build/bin/ownership-audit" #["complete"]
  site false
  IO.println "All required Lean checks passed, including proof, execution and corpus admission."

end AcornGate

/-- Failures never trigger provisioning or fall back to another implementation. -/
def main (args : List String) : IO UInt32 := do
  try
    match args with
    | [] => AcornGate.verify
    | ["diagnostics"] =>
      AcornGate.lake #["build", "acorn-core"]
      AcornGate.audits
      IO.println "Optional mutation diagnostics passed; this is not ordinary merge verification."
    | ["site"] => AcornGate.site false
    | ["site", "write"] => AcornGate.site true
    | _ => throw (IO.userError "usage: acorn-gates [diagnostics | site [write]]")
    return 0
  catch error =>
    IO.eprintln s!"acorn-gates: {error}"
    return 1
