/-
Copyright (c) 2026 acorn contributors. All rights reserved.
Released under the MIT license as described in the repository LICENSE.
Authors: acorn contributors
-/
import Init

/-! # Maintained ownership obligations

The executable inventory is compared with Lake's evaluated configuration and
compiled module owners. A module of the libraries `Acorn`, `AcornVerif` and
`NativeApp` has no entry here: Lake's glob assigns each source below a library
root to that library, and the Regula audit examines every module of a claimed
library. Each other source is a tool listed in `AcornTools.ModuleInventory` or a
module of the documentation site listed below. This routing information does not
assert semantic completeness. Runtime sources receive source/compiled boundary
admission; the Regula audit checks the axioms of every project declaration.
Tooling is the explicit trust boundary listed in `AcornTools.ModuleInventory`,
never an application escape hatch.
-/
namespace AcornOwnership
open Lean

/-- The reviewed modules of the documentation site, the separate Lake package in `site/`;
filesystem discovery rejects missing or extra owners. The site is documentation tooling over
pinned Verso, a trust boundary outside the application's proof claim. -/
def siteModules : Array Name := #[
  `AcornDocs, `AcornDocs.Verification, `AcornSite, `AcornSite.Markdown, `AcornSite.Owners,
  `AcornSite.Reference, `Main
]

/-- Native entry points, checked against both evaluated Lake targets and compiled `main`. -/
def executables : Array (String × Name) := #[
  ("swifttd-native", `Acorn.SwiftTdDriver),
  ("feature-native", `Acorn.FeatureDriver),
  ("control-native", `Acorn.ControlDriver),
  ("temporal-native", `Acorn.TemporalDriver),
  ("agent-native", `Acorn.AgentDriver),
  ("acorn-core", `NativeApp.Main),
  ("acorn-viewer", `NativeApp.Viewer),
  ("browser-kernel", `NativeApp.BrowserKernel),
  ("checkpoint-native", `Acorn.Host.CheckpointDriver),
  ("world-native", `Acorn.WorldDriver),
  ("world-certificates", `Acorn.Host.CertificateDriver),
  ("theorem-count", `AcornTools.TheoremCount),
  ("lean-boundary-audit", `AcornTools.Boundary.Main),
  ("native-audit", `AcornTools.Native.Audit),
  ("ownership-audit", `AcornTools.OwnershipAudit),
  ("corpus-audit", `AcornTools.Corpus.Main),
  ("acorn-gates", `AcornTools.Gate)
]

/-- Required statements about executing definitions must retain their actual execution
references. The entries are the critical entry and transition obligations, the decision
contracts of `Acorn.Decisions` and `AcornVerif.Decisions` that no `@[regula_decision]`
registration requires, and the theorem `AcornDocument.external_listed`. The list is not a
quota or a claim that all mathematical properties are exhausted by the inventory. -/
def anchors : Array (Name × Name × Name) := #[
  (`Acorn.Host.AgentAdmission, `Acorn.Handcrafted.AgentConstruction.admit_iff,
    `Acorn.Handcrafted.AgentConstruction.admit),
  (`Acorn.Host.AgentPrefix, `Acorn.Handcrafted.Agent.prefix_path,
    `Acorn.Handcrafted.Agent.runPrefix),
  (`Acorn.Host.AgentPrefix, `Acorn.Handcrafted.Agent.act_execution,
    `Acorn.Handcrafted.Agent.act),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.Agent.act_parts,
    `Acorn.Handcrafted.Agent.act),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.Agent.act_parts,
    `Acorn.Handcrafted.Agent.actOrdered),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.Agent.choose_keeps,
    `Acorn.Handcrafted.Agent.choose),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.Chosen.learn_rng,
    `Acorn.Handcrafted.Chosen.learn),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.Agent.actOrdered_undrawn,
    `Acorn.Handcrafted.Agent.choose),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.TemporalControl.atBoundary_unplanned,
    `Acorn.Handcrafted.TemporalControl.atBoundary),
  (`Acorn.Options, `Acorn.Features.Skill.optionStep_credit, `Acorn.Features.Skill.optionStep),
  (`Acorn.Options, `Acorn.Features.Skill.optionStep_credit, `Acorn.Features.Skill.optionCredit),
  (`Acorn.Temporal, `Acorn.Features.Skill.stepTemporal_credit,
    `Acorn.Features.Skill.stepTemporal),
  (`Acorn.Temporal, `Acorn.Features.Skill.stepTemporal_credit,
    `Acorn.Features.Skill.creditTemporal),
  (`Acorn.Temporal, `Acorn.Features.Skill.startTemporal_step,
    `Acorn.Features.Skill.startTemporal),
  (`Acorn.Handcrafted.DrawFirst, `Acorn.Handcrafted.TemporalControl.settle_framed,
    `Acorn.Handcrafted.TemporalControl.settle),
  (`Acorn.Handcrafted.DrawFirst, `Acorn.Handcrafted.TemporalControl.drawFirst_total,
    `Acorn.Handcrafted.TemporalControl.drawFirst),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.TemporalControl.drawFirst_keeps,
    `Acorn.Handcrafted.TemporalControl.drawFirst),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.Agent.choose_reward,
    `Acorn.Handcrafted.Agent.choose),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.Agent.choose_drawn,
    `Acorn.Handcrafted.TemporalControl.drawFirst),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.selectWithOperations_settle,
    `Acorn.Handcrafted.TemporalControl.selectWithOperations),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.selectWithOperations_settle,
    `Acorn.Handcrafted.TemporalControl.drawFirst),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.selectWithOperations_settle,
    `Acorn.Handcrafted.TemporalControl.settle),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.actThenLearn_planAfterAct,
    `Acorn.Handcrafted.Agent.actOrdered),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.drawBoundary_start,
    `Acorn.Handcrafted.TemporalControl.drawBoundary),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.dispatchMeta_start,
    `Acorn.Handcrafted.TemporalControl.dispatchMeta),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.dispatchMeta_start,
    `Acorn.Handcrafted.TemporalControl.startOption),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.drawBoundary_unplanned,
    `Acorn.Handcrafted.TemporalControl.drawBoundary),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.drawFirst_assigns,
    `Acorn.Handcrafted.TemporalControl.drawFirst),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.selectWithOperations_form,
    `Acorn.Handcrafted.TemporalControl.selectWithOperations),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.drawFirst_form,
    `Acorn.Handcrafted.TemporalControl.drawFirst),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.drawFirst_form,
    `Acorn.Handcrafted.TemporalControl.settle),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.atBoundary_form,
    `Acorn.Handcrafted.TemporalControl.atBoundary),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.drawBoundary_form,
    `Acorn.Handcrafted.TemporalControl.drawBoundary),
  (`Acorn.Handcrafted.DrawFirst, `Acorn.Handcrafted.TemporalControl.settle_started,
    `Acorn.Handcrafted.TemporalControl.startOption),
  (`AcornVerif.CurrentOak, `AcornVerif.CurrentOak.startOption_event,
    `Acorn.Handcrafted.TemporalControl.startOption),
  (`AcornVerif.CurrentOak, `AcornVerif.CurrentOak.settle_unstarted,
    `Acorn.Handcrafted.TemporalControl.settle),
  (`Acorn.Host.Attempt, `Acorn.Host.DecisionInput.chooseOwned_release,
    `Acorn.Host.DecisionInput.chooseOwned),
  (`Acorn.Host.Attempt, `Acorn.Host.DecisionInput.chooseOwned_release,
    `Acorn.Host.Released.learn),
  (`Acorn.Host.AgentAdmission, `Acorn.Handcrafted.AgentConstruction.callbacks_act,
    `Acorn.Handcrafted.AgentConstruction.callbacks),
  (`Acorn.Host.AgentAdmission, `Acorn.Handcrafted.DefaultConstruction.runPrefix_agent,
    `Acorn.Handcrafted.DefaultConstruction.runPrefix),
  (`Acorn.Timing, `Acorn.StepOrder.parse_spelled, `Acorn.StepOrder.parse),
  (`Acorn.Timing, `Acorn.StepOrder.tag_stored, `Acorn.StepOrder.tag),
  (`Acorn.Options, `Acorn.Features.Skill.optionCredit_frozen,
    `Acorn.Features.Skill.optionCredit),
  (`Acorn.Options, `Acorn.Features.Skill.decide_frozen, `Acorn.Features.Skill.frozenPolicy),
  (`AcornVerif.DrawFirst, `AcornVerif.DrawFirst.closeOption_closing,
    `Acorn.Handcrafted.closingEvent),
  (`Acorn.Timing, `Acorn.Pace.meets_index, `Acorn.Pace.index),
  (`Acorn.Timing, `Acorn.Pace.outcome_fault, `Acorn.Pace.outcome),
  (`Acorn.Timing, `Acorn.Pace.step_fault, `Acorn.Pace.outcome),
  (`Acorn.Timing, `Acorn.Pace.step_fault, `Acorn.Standing.during),
  (`Acorn.Timing, `Acorn.Pace.step_holds, `Acorn.Pace.outcome),
  (`Acorn.Timing, `Acorn.Pace.step_faultless, `Acorn.Pace.meets),
  (`Acorn.Handcrafted.GridWorld, `Acorn.Handcrafted.Grid.interface_timing,
    `Acorn.Handcrafted.Grid.interface),
  (`Acorn.Host.Microduck.Action, `Acorn.Host.Microduck.Action.commands_head,
    `Acorn.Host.Microduck.Action.commands),
  (`Acorn.Host.Microduck.Action, `Acorn.Host.Microduck.Action.commands_powered,
    `Acorn.Host.Microduck.Action.commands),
  (`Acorn.Host.Microduck.Action, `Acorn.Host.Microduck.Action.commands_toggle,
    `Acorn.Host.Microduck.Action.commands),
  (`Acorn.Host.Microduck.Action, `Acorn.Host.Microduck.Action.next_covers,
    `Acorn.Host.Microduck.Action.next),
  (`Acorn.Host.Microduck.Action, `Acorn.Host.Microduck.Action.next_least,
    `Acorn.Host.Microduck.Action.next),
  (`Acorn.Host.Microduck.Bridge, `Acorn.Host.Microduck.Bridge.release_state,
    `Acorn.Host.Microduck.Bridge.release),
  (`Acorn.Host.Microduck.Bridge, `Acorn.Host.Microduck.Bridge.next_covers,
    `Acorn.Host.Microduck.Bridge.next),
  (`Acorn.Host.Microduck.Bridge, `Acorn.Host.Microduck.Bridge.ends_covers,
    `Acorn.Host.Microduck.Bridge.ends),
  (`Acorn.Host.Microduck.Bridge, `Acorn.Host.Microduck.Bridge.ends_bounded,
    `Acorn.Host.Microduck.Bridge.ends),
  (`Acorn.Host.Microduck.Bridge, `Acorn.Host.Microduck.Bridge.release_named,
    `Acorn.Host.Microduck.Bridge.release),
  (`Acorn.Host.Microduck.Bridge, `Acorn.Host.Microduck.Bridge.tick_keeps,
    `Acorn.Host.Microduck.Bridge.tick),
  (`Acorn.Host.Microduck.Bridge, `Acorn.Host.Microduck.Bridge.tick_fresh,
    `Acorn.Host.Microduck.Bridge.tick),
  (`Acorn.Host.Microduck.Bridge, `Acorn.Host.Microduck.Bridge.tick_lapsed,
    `Acorn.Host.Microduck.Bridge.tick),
  (`Acorn.Host.Microduck.Bridge, `Acorn.Host.Microduck.Bridge.ticks_sent,
    `Acorn.Host.Microduck.Bridge.ticks),
  (`Acorn.Host.Microduck.Bridge, `Acorn.Host.Microduck.Bridge.ticks_named,
    `Acorn.Host.Microduck.Bridge.force),
  (`Acorn.Host.Microduck.Bridge, `Acorn.Host.Microduck.Bridge.fault_named,
    `Acorn.Pace.outcome),
  (`Acorn.Host.Microduck.Bridge, `Acorn.Host.Microduck.Bridge.release_outcome,
    `Acorn.Host.Microduck.Bridge.outcome),
  (`Acorn.Decisions, `Acorn.Decisions.microduck_outcome_judged,
    `Acorn.Host.Microduck.Action.outcome),
  (`Acorn.Host.Microduck.Decimal, `Acorn.Host.Microduck.width_bound,
    `Acorn.Host.Microduck.width),
  (`Acorn.Host.Microduck.Decimal, `Acorn.Host.Microduck.Scale.width_bound,
    `Acorn.Host.Microduck.Scale.width),
  (`Acorn.Host.Microduck.Decimal, `Acorn.Host.Microduck.Scale.clamp_value,
    `Acorn.Host.Microduck.Scale.clamp),
  (`Acorn.Host.Microduck.Decimal, `Acorn.Host.Microduck.Decimal.magnitude_bounds,
    `Acorn.Host.Microduck.Decimal.magnitude),
  (`Acorn.Host.Microduck.Decimal, `Acorn.Host.Microduck.Decimal.magnitude_vanishes,
    `Acorn.Host.Microduck.Decimal.magnitude),
  (`Acorn.Host.Microduck.Decimal, `Acorn.Host.Microduck.Decimal.magnitude_beyond,
    `Acorn.Host.Microduck.Decimal.magnitude),
  (`Acorn.Host.Microduck.Decimal, `Acorn.Host.Microduck.Decimal.fixed_clamp,
    `Acorn.Host.Microduck.Decimal.fixed),
  (`Acorn.Host.Microduck.Decimal, `Acorn.Host.Microduck.Decimal.shift_between,
    `Acorn.Host.Microduck.Decimal.shift),
  (`AcornVerif.Decimal, `AcornVerif.Decimal.rounded_nearest,
    `Acorn.Host.Microduck.Decimal.rounded),
  (`AcornVerif.Decimal, `AcornVerif.Decimal.fixed_nearest,
    `Acorn.Host.Microduck.Decimal.fixed),
  (`Acorn.Host.Microduck.Action, `Acorn.Host.Microduck.Action.named_index,
    `Acorn.Host.Microduck.Action.index),
  (`Acorn.Host.Microduck.Action, `Acorn.Host.Microduck.Action.index_named,
    `Acorn.Host.Microduck.Action.named),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.channel_clear,
    `Acorn.Handcrafted.Microduck.channel),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.entries_distinct,
    `Acorn.Handcrafted.Microduck.entries),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.entries_presence,
    `Acorn.Handcrafted.Microduck.entries),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.entries_depth,
    `Acorn.Handcrafted.Microduck.entries),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.entries_gravity,
    `Acorn.Handcrafted.Microduck.entries),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.upright_iff,
    `Acorn.Handcrafted.Microduck.upright),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.fresh_level,
    `Acorn.Handcrafted.Microduck.fresh),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.symbol_valid,
    `Acorn.Handcrafted.Microduck.symbol),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.symbols_zone,
    `Acorn.Handcrafted.Microduck.symbols),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.near_clear,
    `Acorn.Handcrafted.Microduck.clear),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.achieved_iff,
    `Acorn.Handcrafted.Microduck.achieved),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.arm_held,
    `Acorn.Handcrafted.Microduck.arm),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.became_injective,
    `Acorn.Handcrafted.Microduck.became),
  (`Acorn.Handcrafted.Microduck, `Acorn.Handcrafted.Microduck.interface_timing,
    `Acorn.Handcrafted.Microduck.interface),
  (`Acorn.Json, `Acorn.Json.Numeral.scan_formed, `Acorn.Json.Numeral.scan),
  (`Acorn.Json, `Acorn.Json.Numeral.scan_chars, `Acorn.Json.Numeral.scan),
  (`Acorn.Json, `Acorn.Json.Value.numeral_iff, `Acorn.Json.Value.numeral),
  (`Acorn.Host.Microduck.Decimal, `Acorn.Host.Microduck.spelled_append,
    `Acorn.Host.Microduck.spelled),
  (`Acorn.Host.Microduck.Decimal, `Acorn.Host.Microduck.Decimal.read_iff,
    `Acorn.Host.Microduck.Decimal.read),
  (`AcornVerif.Decimal, `AcornVerif.Decimal.ofNumeral_value,
    `Acorn.Host.Microduck.Decimal.ofNumeral),
  (`AcornVerif.Decimal, `AcornVerif.Decimal.spelled_numberOf,
    `Acorn.Host.Microduck.spelled),
  (`AcornVerif.Decimal, `AcornVerif.Decimal.read_nearest,
    `Acorn.Host.Microduck.Decimal.read),
  (`Acorn.Json, `Acorn.Json.Value.member_iff, `Acorn.Json.Value.member),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Policy.named_iff,
    `Acorn.Host.Microduck.Policy.named),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Limits.named_iff,
    `Acorn.Host.Microduck.Limits.named),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.State.read_iff,
    `Acorn.Host.Microduck.State.read),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Depth.read_iff,
    `Acorn.Host.Microduck.Depth.read),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Command.line_asked,
    `Acorn.Host.Microduck.Command.line),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Stream.line_asked,
    `Acorn.Host.Microduck.Stream.line),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Velocity.spelling_formed,
    `Acorn.Host.Microduck.Velocity.spelling),
  (`AcornVerif.Decimal, `AcornVerif.Decimal.spelling_twist,
    `Acorn.Host.Microduck.Velocity.spelling),
  (`Acorn.Json, `Acorn.Json.parse_request,
    `Acorn.Json.parse),
  (`Acorn.Json, `Acorn.Json.Numeral.scan_append,
    `Acorn.Json.Numeral.scan),
  (`Acorn.Json, `Acorn.Json.Numeral.natural_formed,
    `Acorn.Json.Numeral.natural),
  (`Acorn.Host.Microduck.Decimal, `Acorn.Host.Microduck.spelled_digits,
    `Acorn.Host.Microduck.spelled),
  (`Acorn.Host.Microduck.Decimal, `Acorn.Host.Microduck.counted_natural,
    `Acorn.Json.Numeral.natural),
  (`Acorn.Decisions, `Acorn.Decisions.json_parse_value,
    `Acorn.Json.parse),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Line.read_state,
    `Acorn.Host.Microduck.Line.read),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Line.read_depth,
    `Acorn.Host.Microduck.Line.read),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Line.read_unread,
    `Acorn.Host.Microduck.Line.read),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Line.read_notice,
    `Acorn.Host.Microduck.Line.read),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Line.read_result,
    `Acorn.Host.Microduck.Line.read),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Line.read_fault,
    `Acorn.Host.Microduck.Line.read),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Line.read_invalid,
    `Acorn.Host.Microduck.Line.read),
  (`Acorn.Decisions, `Acorn.Decisions.microduck_line_read,
    `Acorn.Host.Microduck.Line.read),
  (`Acorn.Host.Microduck.Wire, `Acorn.Host.Microduck.Depth.read_distances,
    `Acorn.Host.Microduck.Depth.read),
  (`Acorn.Host.Microduck.Sensing, `Acorn.Host.Microduck.Reading.age_exact,
    `Acorn.Host.Microduck.Reading.age),
  (`Acorn.Host.Microduck.Sensing, `Acorn.Host.Microduck.Reading.age_ahead,
    `Acorn.Host.Microduck.Reading.age),
  (`Acorn.Timing, `Acorn.Pace.step_lapsed, `Acorn.Pace.outcome),
  (`Acorn.Timing, `Acorn.Pace.first_starts, `Acorn.Pace.first),
  (`Acorn.Host.Cli, `Acorn.Host.Cli.value_absent, `Acorn.Host.Cli.value),
  (`Acorn.Host.Cli, `Acorn.Host.Cli.value_follows, `Acorn.Host.Cli.value),
  (`Acorn.Host.Cli, `Acorn.Host.Cli.value_missing, `Acorn.Host.Cli.value),
  (`Acorn.Host.Cli, `Acorn.Host.Cli.stepOrderValue_iff, `Acorn.Host.Cli.stepOrderValue),
  (`Acorn.Host.Cli, `Acorn.Host.Cli.stepOrder_iff, `Acorn.Host.Cli.stepOrder),
  (`Acorn.Host.Cli, `Acorn.Host.Cli.stepOrder_refused, `Acorn.Host.Cli.stepOrder),
  (`Acorn.Host.Checkpoint.Admission, `Acorn.Checkpoint.admitHeader_iff,
    `Acorn.Checkpoint.admitHeader),
  (`Acorn.Host.Checkpoint.Admission, `Acorn.Checkpoint.loadCandidate_header,
    `Acorn.Checkpoint.loadCandidate),
  (`Acorn.Host.Checkpoint.Admission, `Acorn.Checkpoint.load_candidate, `Acorn.Checkpoint.load),
  (`AcornVerif.CurrentCheckpoint, `AcornVerif.CurrentCheckpoint.saved_header,
    `Acorn.Checkpoint.saveBytes),
  (`AcornVerif.CurrentCheckpoint, `AcornVerif.CurrentCheckpoint.saved_admitted_order,
    `Acorn.Checkpoint.saveBytes),
  (`AcornVerif.CurrentCheckpoint, `AcornVerif.CurrentCheckpoint.saved_admitted_order,
    `Acorn.Checkpoint.loadCandidate),
  (`AcornVerif.CurrentCheckpoint, `AcornVerif.CurrentCheckpoint.order_edit_refused,
    `Acorn.Checkpoint.decode),
  (`AcornVerif.CurrentCheckpoint, `AcornVerif.CurrentCheckpoint.relabeled_unloaded,
    `Acorn.Checkpoint.loadCandidate),
  (`Acorn.Rng, `Acorn.Rng.fnv_byte, `Acorn.Rng.fnv),
  (`AcornVerif.CurrentCheckpoint, `AcornVerif.CurrentCheckpoint.image_roundtrip,
    `Acorn.Checkpoint.admitPayload),
  (`AcornVerif.CurrentCheckpoint, `AcornVerif.CurrentCheckpoint.image_roundtrip,
    `Acorn.Checkpoint.imagePayload),
  (`Acorn.Host.Attempt, `Acorn.Host.Attempt.complete_learned, `Acorn.Host.Attempt.complete),
  (`Acorn.Host.Runner, `Acorn.Host.runAttemptSteps_complete, `Acorn.Host.runAttemptSteps),
  (`Acorn.Host.Runner, `Acorn.Host.runReleasedSteps_complete, `Acorn.Host.runReleasedSteps),
  (`Acorn.Host.Runner, `Acorn.Host.campaignStep_attempt, `Acorn.Host.campaignStep),
  (`Acorn.Host.AgentInterface, `Acorn.Handcrafted.Agent.callbacks_act,
    `Acorn.Handcrafted.Agent.callbacks),
  (`Acorn.Host.AgentInterface, `Acorn.Handcrafted.Agent.observe_predictions,
    `Acorn.Handcrafted.Agent.observe),
  (`Acorn.Host.AgentInterface, `Acorn.Handcrafted.Agent.grid_inputs,
    `Acorn.Handcrafted.Grid.frame),
  (`AcornVerif.GridCorrespondence, `AcornVerif.GridCorrespondence.initial_eq,
    `Acorn.Handcrafted.Agent.initial),
  (`AcornVerif.GridCorrespondence, `AcornVerif.GridCorrespondence.act_eq,
    `Acorn.Handcrafted.Agent.act),
  (`AcornVerif.GridCorrespondence, `AcornVerif.GridCorrespondence.callback_eq,
    `Acorn.Handcrafted.Agent.callbacks),
  (`AcornVerif.GridCorrespondence, `AcornVerif.GridCorrespondence.restore_eq,
    `Acorn.Handcrafted.Agent.restore),
  (`Acorn.Host.Checkpoint.Frame, `Acorn.Checkpoint.roundtrip, `Acorn.Checkpoint.encode),
  (`Acorn.Host.Checkpoint.Frame, `Acorn.Checkpoint.roundtrip, `Acorn.Checkpoint.decode),
  (`Acorn.Host.Checkpoint.Admission, `Acorn.Checkpoint.load_nonmutation, `Acorn.Checkpoint.load),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.lifetime_admit, `Acorn.Checkpoint.admitLifetime),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.sum_admit, `Acorn.Checkpoint.admitSum),
  (`Acorn.Decisions, `Acorn.Decisions.rails_admit, `Acorn.StepSizeRails.admit),
  (`Acorn.Decisions, `Acorn.Decisions.squared_admit_value, `Acorn.Agreement.admitSquared),
  (`Acorn.Decisions, `Acorn.Decisions.event_admit_value, `Acorn.Features.Event.admit),
  (`Acorn.Decisions, `Acorn.Decisions.last_admit_value, `Acorn.Features.admitLast),
  (`Acorn.Decisions, `Acorn.Decisions.progress_admit_value, `Acorn.Features.Progress.admit),
  (`Acorn.Decisions, `Acorn.Decisions.assignment_admit_value, `Acorn.Features.Assignment.admit),
  (`Acorn.Decisions, `Acorn.Decisions.box_position_checked_value, `Acorn.Host.BoxPosition.checked),
  (`Acorn.Decisions, `Acorn.Decisions.checkpoint_decode_value, `Acorn.Checkpoint.decode),
  (`Acorn.Decisions, `Acorn.Decisions.checkpoint_save, `Acorn.Checkpoint.saveBytes),
  (`Acorn.Decisions, `Acorn.Decisions.checkpoint_load, `Acorn.Checkpoint.load),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.replay_check, `Acorn.Host.ReplayCertificate.check),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.blocked_check, `Acorn.Host.BlockedCertificate.check),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.stance_check, `Acorn.Host.StanceCertificate.check),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.replay_certified, `Acorn.Host.replayCertified),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.region_blocked, `Acorn.Host.regionBlocked),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.stance_certified, `Acorn.Host.stanceCertified),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.terrain_walkable, `Acorn.Host.walkableTile),
  (`Acorn.Decisions, `Acorn.Decisions.less_useful, `Acorn.Features.Lifecycle.lessUseful),
  (`Acorn.Decisions, `Acorn.Decisions.snapshot_consistent,
    `Acorn.Features.PolicySnapshot.consistent),
  (`Acorn.Decisions, `Acorn.Decisions.assignment_admit_using_value,
    `Acorn.Features.Assignment.admitUsing),
  (`Acorn.Decisions, `Acorn.Decisions.controller_step_raw, `Acorn.Features.Controller.stepRaw),
  (`Acorn.Decisions, `Acorn.Decisions.agent_restore, `Acorn.Handcrafted.Agent.restore),
  (`Acorn.Decisions, `Acorn.Decisions.profile_admit, `Acorn.Handcrafted.FeatureProfile.admit),
  (`Acorn.Decisions, `Acorn.Decisions.prediction_advance_raw,
    `Acorn.Handcrafted.PredictionControl.advanceRaw),
  (`Acorn.Decisions, `Acorn.Decisions.list_decode_value, `Acorn.Checkpoint.decodeList),
  (`Acorn.Decisions, `Acorn.Decisions.list_decode_into_value, `Acorn.Checkpoint.decodeListInto),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.demons_admit, `Acorn.Checkpoint.admitDemons),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.feature_image_admit,
    `Acorn.Features.FeatureImage.admit),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.payload_admit, `Acorn.Checkpoint.admitPayload),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.candidate_load, `Acorn.Checkpoint.loadCandidate),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.position_translate,
    `Acorn.Host.Position.translate),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.task_satisfied,
    `Acorn.Host.TaskObservation.satisfied),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.goal_satisfied, `Acorn.Host.World.goalSatisfied),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.interest_potential,
    `Acorn.Features.Interest.potential),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.precision_admit, `Acorn.Agreement.precision),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.profile_admit_accepts,
    `Acorn.Handcrafted.FeatureProfile.admit),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.checkpoint_load_accepts, `Acorn.Checkpoint.load),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.squared_admit_exact,
    `Acorn.Agreement.admitSquared),
  (`Acorn.Decisions, `Acorn.Decisions.capture_follows, `Acorn.Host.Viewer.Capture.follows),
  (`Acorn.Decisions, `Acorn.Decisions.predicate_eval_programs,
    `Acorn.Host.Viewer.ClockProgram.Predicate.eval),
  (`Acorn.Decisions, `Acorn.Decisions.cli_value_found, `Acorn.Host.Cli.value),
  (`Acorn.Decisions, `Acorn.Decisions.lifecycle_candidate, `Acorn.Features.Lifecycle.candidate),
  (`Acorn.Decisions, `Acorn.Decisions.schema_covers_empty, `Acorn.Host.Viewer.schemaCovers),
  (`Acorn.Decisions, `Acorn.Decisions.assignment_identity_value,
    `Acorn.Features.Assignment.identity),
  (`Acorn.Decisions, `Acorn.Decisions.total_observe_value, `Acorn.Agreement.Total.observe),
  (`Acorn.Decisions, `Acorn.Decisions.world_step, `Acorn.Host.World.step),
  (`Acorn.Decisions, `Acorn.Decisions.lifecycle_prefer, `Acorn.Features.Lifecycle.prefer),
  (`Acorn.Decisions, `Acorn.Decisions.episode_end_value,
    `Acorn.Features.TemporalDecision.episodeEnd),
  (`Acorn.Decisions, `Acorn.Decisions.assignment_feature_value, `Acorn.Features.Assignment.feature),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.advance_actions, `Acorn.Host.World.advanceActions),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.terrain_read, `Acorn.Host.terrain),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.tile_kind, `Acorn.Host.World.tileKind),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.pay_and_act, `Acorn.Host.payAndAct),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.perform_action, `Acorn.Host.performAction),
  (`Acorn.Decisions, `Acorn.Decisions.candidate_of_weight_value, `Acorn.Features.candidateOfWeight),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.world_enterable, `Acorn.Host.World.enterable),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.task_observed,
    `Acorn.Host.TaskObservation.satisfied),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.exp_saturation, `Acorn.Portable.expSaturation),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.sum_admit_value, `Acorn.Checkpoint.admitSum),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.stance_certified_refused,
    `Acorn.Host.stanceCertified),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.stance_check_refused,
    `Acorn.Host.StanceCertificate.check),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.blocked_check_refused,
    `Acorn.Host.BlockedCertificate.check),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.demons_admit_value, `Acorn.Checkpoint.admitDemons),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.feature_image_admit_value,
    `Acorn.Features.FeatureImage.admit),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.payload_admit_value,
    `Acorn.Checkpoint.admitPayload),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.candidate_load_value,
    `Acorn.Checkpoint.loadCandidate),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.interest_potential_declared,
    `Acorn.Features.Interest.potential),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.profile_admit_accepts_value,
    `Acorn.Handcrafted.FeatureProfile.admit),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.profile_admit_sound,
    `Acorn.Handcrafted.FeatureProfile.admit),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.rank_index, `Acorn.Host.Endurance.rankIndex),
  (`AcornTools.Corpus.Documents, `AcornDocument.external_listed, `AcornDocument.external),
  (`Acorn.Host.Viewer.Admission, `Acorn.Host.Viewer.Admission.rejected_preserves_history,
    `Acorn.Host.Viewer.Admission.receive),
  (`Acorn.Host.Viewer.Admission, `Acorn.Host.Viewer.Admission.stored_capture,
    `Acorn.Host.Viewer.Admission.receive),
  (`Acorn.Host.Viewer.Lifecycle, `Acorn.Host.Viewer.Lifecycle.stale_preserves,
    `Acorn.Host.Viewer.Lifecycle.admit),
  (`Acorn.Host.Viewer.Lifecycle, `Acorn.Host.Viewer.Lifecycle.retire_revokes,
    `Acorn.Host.Viewer.Lifecycle.retire),
  (`Acorn.Host.Viewer.BrowserSchema, `Acorn.Host.Viewer.browserSchema_execution,
    `Acorn.Host.Viewer.coreTelemetry),
  (`Acorn.Host.Viewer.BrowserRecord, `Acorn.Host.Viewer.browserRecord_keys,
    `Acorn.Host.Viewer.browserRecordFields),
  (`Acorn.Host.Viewer.BrowserStore, `Acorn.Host.Viewer.browserColumns_live,
    `Acorn.Host.Viewer.browserColumns),
  (`NativeApp.MutationAudit, `NativeApp.AuditArm.incumbent_profile,
    `NativeApp.AuditArm.construction),
  (`AcornVerif.CurrentCertificates, `AcornVerif.CurrentCertificates.replay_feasible,
    `Acorn.Host.replayCertified),
  (`AcornVerif.CurrentCertificates, `AcornVerif.CurrentCertificates.blocked_outside,
    `Acorn.Host.regionBlocked),
  (`AcornVerif.CurrentCertificates, `AcornVerif.CurrentCertificates.stance_harvest,
    `Acorn.Host.stanceCertified)
]

/-- Required native entry dependencies after proof erasure. These are routing
obligations; the IR graph alone does not prove control-flow or argument semantics.
Erased ANSI and checksum parameters select the compiler's reduced-arity owners. -/
def entryUses : Array (Name × Array Name) := #[
  (`NativeApp.Main, #[`NativeApp.streamingOptions, `Acorn.Host.Viewer.runNativeCampaign,
    `Acorn.Host.StopFlag.withCommands._redArg,
    `Acorn.Handcrafted.Agent.callbacks, `Acorn.Handcrafted.AgentConstruction.callbacks,
    `Acorn.Handcrafted.AgentConstruction.runCampaign,
    `Acorn.Checkpoint.Store.hooks,
    `Acorn.Host.runAnsi._redArg, `Acorn.Host.agentChecksum._redArg, `NativeApp.runMutationAudit,
    `NativeApp.AuditArm.construction]),
  (`NativeApp.Viewer, #[`NativeApp.runViewer, `Acorn.Host.Viewer.ViewerOptions.decode,
    `Acorn.Host.Viewer.Supervisor.new, `Acorn.Host.Viewer.Supervisor.step]),
  (`NativeApp.BrowserKernel, #[`Acorn.Host.Viewer.browserKernelJavascript]),
  (`Acorn.SwiftTdDriver, #[`Acorn.SwiftTdDriver.execute]),
  (`Acorn.FeatureDriver, #[`Acorn.FeatureDriver.execute]),
  (`Acorn.ControlDriver, #[`Acorn.ControlDriver.execute]),
  (`Acorn.TemporalDriver, #[`Acorn.TemporalDriver.execute]),
  (`Acorn.AgentDriver, #[`Acorn.AgentDriver.execute]),
  (`Acorn.WorldDriver, #[`Acorn.WorldDriver.execute]),
  (`Acorn.Host.CheckpointDriver, #[`Acorn.Host.CheckpointDriver.dispatch]),
  (`Acorn.Host.CertificateDriver, #[`Acorn.Host.CertificateDriver.execute,
    `Acorn.Host.replayCertified, `Acorn.Host.regionBlocked, `Acorn.Host.stanceCertified]),
  (`AcornTools.Boundary.Main, #[`AcornBoundaryAudit.command]),
  (`AcornTools.TheoremCount, #[`AcornTheoremCount.inventory]),
  (`AcornTools.Native.Audit, #[`AcornNativeAudit.audit]),
  (`AcornTools.OwnershipAudit, #[`AcornOwnershipAudit.compiled]),
  (`AcornTools.Corpus.Main, #[`AcornCorpus.check]),
  (`AcornTools.Gate, #[`AcornGate.verify])
]

end AcornOwnership
