/-
Copyright (c) 2026 acorn contributors. All rights reserved.
Released under the MIT license as described in the repository LICENSE.
Authors: acorn contributors
-/
import Lean

/-! # Maintained ownership obligations

The executable inventory is compared with Lake's evaluated configuration and
compiled module owners. The module inventory is a closed admission boundary:
new files need an explicit ownership decision, including new tools or proof
modules. This routing information does not assert semantic completeness.
Runtime sources receive source/compiled boundary admission; every project
proof receives dependent-axiom auditing. Tooling is the explicit trust boundary
listed in `AcornTools.ModuleInventory`, never an application escape hatch.
-/
namespace AcornOwnership
open Lean

/-- All reviewed maintained modules; filesystem discovery rejects missing or extra owners. -/
def modules : Array Name := #[
  `AcornTools,
  `Acorn, `Acorn.Constants, `Acorn.Admission, `Acorn.AgentDriver,
  `Acorn.Arithmetic, `Acorn.Average, `Acorn.Control,
  `Acorn.ControlDriver, `Acorn.Conversion, `Acorn.Demon,
  `Acorn.Encoding, `Acorn.Exploration, `Acorn.FeatureConstants,
  `Acorn.FeatureConsumers, `Acorn.FeatureDriver, `Acorn.FeatureHistory,
  `Acorn.FeatureLifecycle, `Acorn.FeatureModelInput, `Acorn.FeatureRanking,
  `Acorn.FeatureReferences, `Acorn.FeatureRefresh, `Acorn.FeatureRestore,
  `Acorn.Features, `Acorn.Handcrafted.Agent, `Acorn.Handcrafted.AgentAlignment,
  `Acorn.Handcrafted.AgentEpisodes, `Acorn.Handcrafted.Cumulants, `Acorn.Handcrafted.FeatureProfile,
  `Acorn.Handcrafted.Observation, `Acorn.Handcrafted.PredictionControl, `Acorn.Handcrafted.TemporalControl,
  `Acorn.Handcrafted.TemporalProfile, `Acorn.Host.AgentAdmission, `Acorn.Host.AgentArguments,
  `Acorn.Host.AgentAudit, `Acorn.Host.AgentDiagnostics, `Acorn.Host.AgentInterface, `Acorn.Host.AgentPrefix,
  `Acorn.Host.AuditPins, `Acorn.Host.Ansi, `Acorn.Host.Attempt, `Acorn.Host.Baseline,
  `Acorn.Host.Campaign, `Acorn.Host.Checkpoint.Admission, `Acorn.Host.Checkpoint.Codec,
  `Acorn.Host.Checkpoint.Frame, `Acorn.Host.Checkpoint.IO, `Acorn.Host.Checkpoint.Schema,
  `Acorn.Host.Checkpoint.Size, `Acorn.Host.Checkpoint.Snapshot, `Acorn.Host.CheckpointDiagnostic,
  `Acorn.Host.CheckpointDriver, `Acorn.Host.Cli, `Acorn.Host.Control,
  `Acorn.Host.Curriculum, `Acorn.Host.Endurance, `Acorn.Host.Geometry,
  `Acorn.Host.Metrics, `Acorn.Host.Observation, `Acorn.Host.Runner,
  `Acorn.Host.Task, `Acorn.Host.TemporalProfile, `Acorn.Host.Terrain,
  `Acorn.Host.Viewer.Admission, `Acorn.Host.Viewer.AgentTelemetry, `Acorn.Host.Viewer.Broadcast,
  `Acorn.Host.Viewer.BrowserMath, `Acorn.Host.Viewer.BrowserNat, `Acorn.Host.Viewer.BrowserSchema,
  `Acorn.Host.Viewer.Buffer, `Acorn.Host.Viewer.ClockProgram, `Acorn.Host.Viewer.ControlRequest,
  `Acorn.Host.Viewer.ControlTelemetry, `Acorn.Host.Viewer.CoreTelemetry, `Acorn.Host.Viewer.FeatureTelemetry, `Acorn.Host.Viewer.GoalProtocol, `Acorn.Host.Viewer.GoalAchievement,
  `Acorn.Host.Viewer.HttpServer, `Acorn.Host.Viewer.IdentityHandshake, `Acorn.Host.Viewer.Lifecycle,
  `Acorn.Host.Viewer.LifetimeTelemetry, `Acorn.Host.Viewer.Line, `Acorn.Host.Viewer.LogPump,
  `Acorn.Host.Viewer.MapCodec, `Acorn.Host.Viewer.NativeContext, `Acorn.Host.Viewer.NativeCore,
  `Acorn.Host.Viewer.Options, `Acorn.Host.Viewer.PersistedState, `Acorn.Host.Viewer.PipePump,
  `Acorn.Host.Viewer.ProcessOwner, `Acorn.Host.Viewer.Retry, `Acorn.Host.Viewer.RunDirectory,
  `Acorn.Host.Viewer.Sensed, `Acorn.Host.Viewer.SupervisedProcess, `Acorn.Host.Viewer.Supervisor,
  `Acorn.Host.Viewer.TelemetryValue, `Acorn.Host.Viewer.Wire, `Acorn.Host.Viewer.WireNumber,
  `Acorn.Host.Viewer.WorldMemory, `Acorn.Host.Viewer.WorldTelemetry, `Acorn.Host.WorldDynamics,
  `Acorn.Host.WorldGeneration, `Acorn.Host.WorldObservation, `Acorn.Host.WorldState,
  `Acorn.Agreement, `Acorn.Lifetime, `Acorn.Models, `Acorn.Options,
  `Acorn.Planning, `Acorn.Policy, `Acorn.Portable,
  `Acorn.Provenance, `Acorn.Rng, `Acorn.Rounding,
  `Acorn.Sarsa, `Acorn.Shuffle, `Acorn.State,
  `Acorn.SwiftTd, `Acorn.SwiftTdDriver, `Acorn.Temporal,
  `Acorn.TemporalDriver, `Acorn.Word, `Acorn.WorldDriver,
  `Acorn.Json,
  `AcornVerif,
  `AcornVerif.AgreementLifecycle, `AcornVerif.AgreementInterpretation, `AcornVerif.AgreementPrecision,
  `AcornVerif.AgreementReturn, `AcornVerif.AgreementTelemetryPrecision, `AcornVerif.CurrentAgreement,
  `AcornVerif.AverageReward,
  `AcornVerif.Axioms, `AcornVerif.BigWorld, `AcornVerif.Checkpoint,
  `AcornVerif.CurrentBackupBounds, `AcornVerif.CurrentConstants, `AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirementRounding,
  `AcornVerif.CurrentReplacement,
  `AcornVerif.CurrentAgent, `AcornVerif.CurrentArithmetic, `AcornVerif.CurrentCheckpoint,
  `AcornVerif.CurrentControl, `AcornVerif.CurrentDivision, `AcornVerif.CurrentExponential,
  `AcornVerif.CurrentFeatureConsumers, `AcornVerif.CurrentFloat, `AcornVerif.CurrentFloor,
  `AcornVerif.CurrentIntervals, `AcornVerif.CurrentLearner, `AcornVerif.CurrentLearnerArithmetic,
  `AcornVerif.CurrentLifetime, `AcornVerif.CurrentLifetimeArithmetic, `AcornVerif.CurrentLogarithm,
  `AcornVerif.CurrentModelArithmetic, `AcornVerif.CurrentModels, `AcornVerif.CurrentOperations,
  `AcornVerif.CurrentOrder, `AcornVerif.CurrentPortable, `AcornVerif.CurrentPower,
  `AcornVerif.CurrentPrediction, `AcornVerif.CurrentReduction, `AcornVerif.CurrentRng,
  `AcornVerif.CurrentRunner, `AcornVerif.CurrentSeries, `AcornVerif.CurrentState,
  `AcornVerif.CurrentTemporal, `AcornVerif.CurrentWorld, `AcornVerif.Endurance,
  `AcornVerif.Energy, `AcornVerif.Exploration,
  `AcornVerif.ModelConstants, `AcornVerif.MetaGradient, `AcornVerif.Options,
  `AcornVerif.Projection,
  `AcornVerif.Retirement, `AcornVerif.Rng, `AcornVerif.StepSize,
  `AcornVerif.TemporalSupport,
  `AcornVerif.Traces, `AcornVerif.WorldGoals, `Bootstrap,
  `AcornTools.Boundary.Audit, `AcornTools.Boundary.Main, `AcornTools.Corpus.Audit, `AcornTools.Corpus.Main, `AcornTools.Boundary.Departures, `AcornTools.Corpus.Browser, `AcornTools.Corpus.Documents, `AcornTools.Corpus.Pins, `AcornTools.Gate, `AcornTools.ModuleInventory,
  `NativeApp, `NativeApp.Assets, `NativeApp.BrowserKernel,
  `NativeApp.Build, `NativeApp.Core, `NativeApp.Main, `NativeApp.Report, `NativeApp.MutationAudit,
  `Acorn.Host.Viewer.NativeResources, `AcornTools.Native.Audit,
  `AcornVerif.Resource.WordKernel,
  `AcornTools.Native.Resources, `AcornTools.Native.Routes, `NativeApp.Viewer, `AcornTools.Ownership,
  `AcornTools.OwnershipAudit, `AcornTools.OwnershipSource, `AcornTools.Theorems, `AcornTools.TheoremCount
]

/-- Native entry points, checked against both evaluated Lake targets and compiled `main`. -/
def executables : Array (String × Name) := #[
  ("swifttd-native", `Acorn.SwiftTdDriver),
  ("feature-native", `Acorn.FeatureDriver),
  ("control-native", `Acorn.ControlDriver),
  ("temporal-native", `Acorn.TemporalDriver),
  ("agent-native", `Acorn.AgentDriver),
  ("acorn-core", `NativeApp.Main),
  ("acorn-viewer", `NativeApp.Viewer),
  ("browser-kernel", `NativeApp.BrowserKernel),
  ("checkpoint-native", `Acorn.Host.CheckpointDriver),
  ("world-native", `Acorn.WorldDriver),
  ("theorem-count", `AcornTools.TheoremCount),
  ("lean-boundary-audit", `AcornTools.Boundary.Main),
  ("native-audit", `AcornTools.Native.Audit),
  ("ownership-audit", `AcornTools.OwnershipAudit),
  ("corpus-audit", `AcornTools.Corpus.Main),
  ("acorn-gates", `AcornTools.Gate)
]

/-- Required composition statements must retain their actual execution references.
These are critical entry/transition obligations, not a quota or a claim that
all mathematical properties are exhausted by the inventory. -/
def anchors : Array (Name × Name × Name) := #[
  (`AcornVerif.CurrentWorld, `AcornVerif.CurrentWorld.standard_config_exists,
    `Acorn.Host.WorldConfig.standard),
  (`AcornVerif.CurrentWorld, `AcornVerif.CurrentWorld.standard_body_translation,
    `Acorn.Host.Position.translate),
  (`AcornVerif.CurrentWorld, `AcornVerif.CurrentWorld.standard_spiral_coordinates,
    `Acorn.Host.Coordinate.checked),
  (`AcornVerif.CurrentRunner, `AcornVerif.CurrentRunner.survival_plan_exists,
    `Acorn.Host.CampaignPlan.admit),
  (`AcornVerif.CurrentRunner, `AcornVerif.CurrentRunner.initial_cursor_exists,
    `Acorn.Host.CampaignPlan.initial),
  (`AcornVerif.CurrentRunner, `AcornVerif.CurrentRunner.achieved_next_goal,
    `Acorn.Host.atAttemptBoundary),
  (`AcornVerif.CurrentRunner, `AcornVerif.CurrentRunner.standard_first_goals,
    `Acorn.Host.standardCurriculum),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.survival_completion,
    `Acorn.Host.World.goalSatisfied),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.survival_prefix_clock,
    `Acorn.Host.World.time),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.ranked_survival_native_step,
    `Acorn.Host.DecisionInput.selectOwned),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.ranked_survival_native_step,
    `Acorn.Host.OwnedStep.environment),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.ranked_survival_native_step,
    `Acorn.Host.OwnedEnvironment.record),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_initial_survival,
    `Acorn.Handcrafted.Agent.initial),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_initial_survival,
    `Acorn.Host.World.initial),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.finish_carried,
    `Acorn.Host.Attempt.finish),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.zero_retire,
    `Acorn.NumericState.retireIndex),
  (`AcornVerif.CurrentControl, `AcornVerif.CurrentControl.zero_controller_retire,
    `Acorn.Features.Controller.retire),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_model_retire,
    `Acorn.Features.Model.retire),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_retire,
    `Acorn.Handcrafted.Agent.retire),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_act,
    `Acorn.Handcrafted.Agent.act),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_finish,
    `Acorn.Handcrafted.TemporalControl.finish),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_step,
    `Acorn.Handcrafted.TemporalControl.step),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_aligned_step,
    `Acorn.Handcrafted.TemporalControl.alignedStep),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_serve,
    `Acorn.Handcrafted.TemporalControl.serve),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_continuing,
    `Acorn.Features.Skill.decideOption),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_continuing,
    `Acorn.Handcrafted.TemporalControl.stepOption),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_close_active,
    `Acorn.Handcrafted.TemporalControl.closeOption),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_selection,
    `Acorn.Handcrafted.TemporalControl.selectWithOperations),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_refresh,
    `Acorn.Handcrafted.TemporalControl.refreshFree),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_plan,
    `Acorn.Handcrafted.TemporalControl.planFree),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_plan,
    `Acorn.Features.planningBoundary),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_dispatch,
    `Acorn.Handcrafted.TemporalControl.dispatchMeta),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_boundary,
    `Acorn.Handcrafted.TemporalControl.atBoundary),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_prepare,
    `Acorn.Handcrafted.TemporalControl.prepareSelection),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_draw_credit,
    `Acorn.Handcrafted.TemporalControl.drawMeta),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_draw_credit,
    `Acorn.Handcrafted.TemporalControl.learnMeta),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranked_initial,
    `Acorn.Handcrafted.Agent.initial),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_skill_state_with_skill,
    `Acorn.Handcrafted.TemporalControl.withSkill),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_skill_state_potential,
    `Acorn.Features.Interest.potential),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_skill_state_continuing,
    `Acorn.Handcrafted.TemporalControl.stepOption),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_skill_state_dispatch,
    `Acorn.Handcrafted.TemporalControl.dispatchMeta),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_skill_state_close_snapshot,
    `Acorn.Handcrafted.TemporalControl.closeOption),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_skill_state_close_active,
    `Acorn.Handcrafted.TemporalControl.closeOption),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_neutral_skill_initial,
    `Acorn.Features.Skill.initial),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_neutral_skill_begin,
    `Acorn.Features.Skill.beginTemporal),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_neutral_skill_continuing,
    `Acorn.Features.Skill.decideOption),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_neutral_skill_end_snapshot,
    `Acorn.Features.Skill.endTemporal),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.zero_mul_finite,
    `Acorn.Binary32.mul),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.zero_plan_identity,
    `Acorn.NumericState.planStep),
  (`AcornVerif.CurrentControl, `AcornVerif.CurrentControl.rule_power_finite,
    `Acorn.Portable.pow),
  (`AcornVerif.CurrentControl, `AcornVerif.CurrentControl.zero_gap_accumulate,
    `Acorn.Features.CreditGap.accumulate),
  (`AcornVerif.CurrentControl, `AcornVerif.CurrentControl.zero_controller_plan,
    `Acorn.Features.Controller.plan),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_model_initial,
    `Acorn.Features.Model.initial),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_model_begin,
    `Acorn.Features.Model.begin),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_model_step,
    `Acorn.Features.Model.step),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_model_terminal,
    `Acorn.Features.Model.terminal),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_model_target,
    `Acorn.Features.Model.predict),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_backup_controller,
    `Acorn.Features.PlanningResult.backup),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_planning_controller,
    `Acorn.Features.planningBoundary),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.neutral_potential,
    `Acorn.Features.Interest.potential),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_neutral_targets,
    `Acorn.Features.terminalCumulant),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_neutral_terminal_snapshot,
    `Acorn.Features.Skill.terminateOption),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.zero_first_snapshot,
    `Acorn.NumericState.learnFirstLoop),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.zero_clear,
    `Acorn.NumericState.clearTransient),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.zero_prediction,
    `Acorn.NumericState.predict),
  (`AcornVerif.CurrentControl, `AcornVerif.CurrentControl.zero_controller_initial,
    `Acorn.Features.Controller.initial),
  (`AcornVerif.CurrentControl, `AcornVerif.CurrentControl.zero_predict_all,
    `Acorn.Features.Controller.predictAll),
  (`AcornVerif.CurrentControl, `AcornVerif.CurrentControl.zero_controller_clear,
    `Acorn.Features.Controller.clear),
  (`AcornVerif.CurrentControl, `AcornVerif.CurrentControl.zero_values_step,
    `Acorn.Features.Controller.valuesStep),
  (`AcornVerif.CurrentControl, `AcornVerif.CurrentControl.zero_controller_step,
    `Acorn.Features.Controller.step),
  (`AcornVerif.CurrentControl, `AcornVerif.CurrentControl.zero_controller_terminal,
    `Acorn.Features.Controller.terminal),
  (`AcornVerif.CurrentControl, `AcornVerif.CurrentControl.zero_snapshot_best,
    `Acorn.Features.Controller.snapshot),
  (`AcornVerif.CurrentControl, `AcornVerif.CurrentControl.zero_draw_policy_step,
    `Acorn.Features.PolicySnapshot.draw),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_rank_assignments,
    `Acorn.Features.rankAssignments),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranking_initial,
    `Acorn.Features.DemonBank.initial),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_ranking_advance,
    `Acorn.Handcrafted.PredictionControl.advance),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_neutral_refresh,
    `Acorn.Features.FreeDispatch.refreshRanked),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_meta_agent_initial,
    `Acorn.Handcrafted.Agent.initial),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_continuation_close_snapshot,
    `Acorn.Handcrafted.TemporalControl.closeOption),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.zero_initial,
    `Acorn.NumericState.initial),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.zero_first_loop,
    `Acorn.NumericState.learnFirstLoop),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.zero_second_loop,
    `Acorn.NumericState.learnSecondLoop),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.zero_step,
    `Acorn.NumericState.step),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.zero_begin,
    `Acorn.NumericState.beginTrajectory),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.zero_terminal,
    `Acorn.NumericState.terminalStep),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_continuation_agent_initial,
    `Acorn.Handcrafted.Agent.initial),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_continuation_skill_begin,
    `Acorn.Features.Skill.beginTemporal),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_continuation_skill_step,
    `Acorn.Features.Skill.stepTemporal),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_continuation_end,
    `Acorn.Features.Skill.endTemporal),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.zero_continuation_close,
    `Acorn.Handcrafted.TemporalControl.closeOption),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.step_two_refresh_cold,
    `Acorn.Handcrafted.TemporalControl.step),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.cold_model_refuses,
    `Acorn.Features.Lifecycle.tryRetire),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.retire_cold_model,
    `Acorn.Handcrafted.Agent.retire),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.act_two_refresh_changes,
    `Acorn.Handcrafted.Agent.act),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.boolean_cumulants,
    `Acorn.Handcrafted.Cumulant.eval),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.boolean_encoding_bound,
    `Acorn.Handcrafted.encodeObservation),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.boolean_prefix_admitted,
    `Acorn.Handcrafted.Agent.runPrefix),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.neutral_interruption_iff,
    `Acorn.Features.Skill.decideOption),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.neutral_terminal_error_nonnegative,
    `Acorn.Features.terminalCumulant),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.retirement_enabled_iff,
    `Acorn.Features.Lifecycle.tryRetire),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.act_history_count,
    `Acorn.Handcrafted.Agent.act),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.first_option_model,
    `Acorn.Features.Skill.stepTemporal),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.clear_values_step,
    `Acorn.Features.Controller.valuesStep),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.first_option_policy,
    `Acorn.Features.Skill.beginTemporal),
  (`AcornVerif.CurrentReplacement, `AcornVerif.CurrentReplacement.first_option_policy,
    `Acorn.Features.Skill.stepTemporal),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.one_action_trajectory_cold,
    `Acorn.NumericState.beginTrajectory),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.one_action_trajectory_cold,
    `Acorn.NumericState.terminalStep),
  (`AcornVerif.CurrentRetirement, `AcornVerif.CurrentRetirement.episode_sensitivity_anchor,
    `Acorn.NumericState.secondLoopElement),
  (`Acorn.Host.AgentAdmission, `Acorn.Handcrafted.AgentConstruction.admit_iff,
    `Acorn.Handcrafted.AgentConstruction.admit),
  (`Acorn.Host.AgentPrefix, `Acorn.Handcrafted.Agent.prefix_path,
    `Acorn.Handcrafted.Agent.runPrefix),
  (`Acorn.Host.AgentPrefix, `Acorn.Handcrafted.Agent.act_execution,
    `Acorn.Handcrafted.Agent.act),
  (`Acorn.Host.AgentInterface, `Acorn.Handcrafted.Agent.callbacks_act,
    `Acorn.Handcrafted.Agent.callbacks),
  (`Acorn.Host.AgentInterface, `Acorn.Handcrafted.Agent.observe_predictions,
    `Acorn.Handcrafted.Agent.observe),
  (`Acorn.Host.Checkpoint.Frame, `Acorn.Checkpoint.roundtrip, `Acorn.Checkpoint.encode),
  (`Acorn.Host.Checkpoint.Frame, `Acorn.Checkpoint.roundtrip, `Acorn.Checkpoint.decode),
  (`Acorn.Host.Checkpoint.Admission, `Acorn.Checkpoint.load_nonmutation, `Acorn.Checkpoint.load),
  (`Acorn.Host.Viewer.Admission, `Acorn.Host.Viewer.Admission.rejected_preserves_history,
    `Acorn.Host.Viewer.Admission.receive),
  (`Acorn.Host.Viewer.Admission, `Acorn.Host.Viewer.Admission.stored_capture,
    `Acorn.Host.Viewer.Admission.receive),
  (`Acorn.Host.Viewer.Lifecycle, `Acorn.Host.Viewer.Lifecycle.stale_preserves,
    `Acorn.Host.Viewer.Lifecycle.admit),
  (`Acorn.Host.Viewer.Lifecycle, `Acorn.Host.Viewer.Lifecycle.retire_revokes,
    `Acorn.Host.Viewer.Lifecycle.retire),
  (`Acorn.Host.Viewer.BrowserSchema, `Acorn.Host.Viewer.browserSchema_execution,
    `Acorn.Host.Viewer.coreTelemetry),
  (`NativeApp.MutationAudit, `NativeApp.AuditArm.incumbent_profile,
    `NativeApp.AuditArm.construction)
]

/-- Required native entry dependencies after proof erasure. These are routing
obligations; the IR graph alone does not prove control-flow or argument semantics.
Erased ANSI and checksum parameters select the compiler's reduced-arity owners. -/
def entryUses : Array (Name × Array Name) := #[
  (`NativeApp.Main, #[`NativeApp.streamingOptions, `Acorn.Host.Viewer.runNativeCampaign,
    `Acorn.Host.StopFlag.withCommands._redArg,
    `Acorn.Handcrafted.Agent.callbacks, `Acorn.Checkpoint.Store.hooks,
    `Acorn.Host.runAnsi._redArg, `Acorn.Host.agentChecksum._redArg, `NativeApp.runMutationAudit,
    `NativeApp.AuditArm.construction]),
  (`NativeApp.Viewer, #[`NativeApp.runViewer, `Acorn.Host.Viewer.ViewerOptions.decode,
    `Acorn.Host.Viewer.Supervisor.new, `Acorn.Host.Viewer.Supervisor.step]),
  (`NativeApp.BrowserKernel, #[`Acorn.Host.Viewer.browserKernelJavascript]),
  (`Acorn.SwiftTdDriver, #[`Acorn.SwiftTdDriver.execute]),
  (`Acorn.FeatureDriver, #[`Acorn.FeatureDriver.execute]),
  (`Acorn.ControlDriver, #[`Acorn.ControlDriver.execute]),
  (`Acorn.TemporalDriver, #[`Acorn.TemporalDriver.execute]),
  (`Acorn.AgentDriver, #[`Acorn.AgentDriver.execute]),
  (`Acorn.WorldDriver, #[`Acorn.WorldDriver.execute]),
  (`Acorn.Host.CheckpointDriver, #[`Acorn.Host.CheckpointDriver.dispatch]),
  (`AcornTools.Boundary.Main, #[`AcornBoundaryAudit.command]),
  (`AcornTools.TheoremCount, #[`AcornTheoremCount.inventory]),
  (`AcornTools.Native.Audit, #[`AcornNativeAudit.audit]),
  (`AcornTools.OwnershipAudit, #[`AcornOwnershipAudit.compiled]),
  (`AcornTools.Corpus.Main, #[`AcornCorpus.check]),
  (`AcornTools.Gate, #[`AcornGate.verify])
]

end AcornOwnership
