/-
Copyright (c) 2026 acorn contributors. All rights reserved.
Released under the MIT license as described in the repository LICENSE.
Authors: acorn contributors
-/
import Init

/-! # Maintained ownership obligations

The executable inventory is compared with Lake's evaluated configuration and
compiled module owners. A module of the libraries `Acorn`, `AcornVerif` and
`NativeApp` has no entry here: Lake's glob assigns each source below a library
root to that library, and the Regula audit examines every module of a claimed
library. Each other source is a tool listed in `AcornTools.ModuleInventory` or a
module of the documentation site listed below. This routing information does not
assert semantic completeness. Runtime sources receive source/compiled boundary
admission; the Regula audit checks the axioms of every project declaration.
Tooling is the explicit trust boundary listed in `AcornTools.ModuleInventory`,
never an application escape hatch.
-/
namespace AcornOwnership
open Lean

/-- The reviewed modules of the documentation site, the separate Lake package in `site/`;
filesystem discovery rejects missing or extra owners. The site is documentation tooling over
pinned Verso, a trust boundary outside the application's proof claim. -/
def siteModules : Array Name := #[
  `AcornDocs, `AcornDocs.Verification, `AcornSite, `AcornSite.Markdown, `AcornSite.Owners,
  `AcornSite.Reference, `Main
]

/-- Native entry points, checked against both evaluated Lake targets and compiled `main`. -/
def executables : Array (String × Name) := #[
  ("swifttd-native", `Acorn.SwiftTdDriver),
  ("feature-native", `Acorn.FeatureDriver),
  ("control-native", `Acorn.ControlDriver),
  ("temporal-native", `Acorn.TemporalDriver),
  ("agent-native", `Acorn.AgentDriver),
  ("acorn-core", `NativeApp.Main),
  ("acorn-viewer", `NativeApp.Viewer),
  ("browser-kernel", `NativeApp.BrowserKernel),
  ("checkpoint-native", `Acorn.Host.CheckpointDriver),
  ("world-native", `Acorn.WorldDriver),
  ("world-certificates", `Acorn.Host.CertificateDriver),
  ("theorem-count", `AcornTools.TheoremCount),
  ("lean-boundary-audit", `AcornTools.Boundary.Main),
  ("native-audit", `AcornTools.Native.Audit),
  ("ownership-audit", `AcornTools.OwnershipAudit),
  ("corpus-audit", `AcornTools.Corpus.Main),
  ("acorn-gates", `AcornTools.Gate)
]

/-- Required statements about executing definitions must retain their actual execution
references. The entries are the critical entry and transition obligations, the decision
contracts of `Acorn.Decisions` and `AcornVerif.Decisions` that no `@[regula_decision]`
registration requires, and the theorem `AcornDocument.external_listed`. The list is not a
quota or a claim that all mathematical properties are exhausted by the inventory. -/
def anchors : Array (Name × Name × Name) := #[
  (`Acorn.Host.AgentAdmission, `Acorn.Handcrafted.AgentConstruction.admit_iff,
    `Acorn.Handcrafted.AgentConstruction.admit),
  (`Acorn.Host.AgentPrefix, `Acorn.Handcrafted.Agent.prefix_path,
    `Acorn.Handcrafted.Agent.runPrefix),
  (`Acorn.Host.AgentPrefix, `Acorn.Handcrafted.Agent.act_execution,
    `Acorn.Handcrafted.Agent.act),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.Agent.act_parts,
    `Acorn.Handcrafted.Agent.act),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.Agent.act_parts,
    `Acorn.Handcrafted.Agent.actOrdered),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.Agent.choose_keeps,
    `Acorn.Handcrafted.Agent.choose),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.Chosen.learn_rng,
    `Acorn.Handcrafted.Chosen.learn),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.Agent.actOrdered_undrawn,
    `Acorn.Handcrafted.Agent.choose),
  (`Acorn.Handcrafted.StepParts, `Acorn.Handcrafted.TemporalControl.atBoundary_unplanned,
    `Acorn.Handcrafted.TemporalControl.atBoundary),
  (`Acorn.Host.Attempt, `Acorn.Host.DecisionInput.chooseOwned_release,
    `Acorn.Host.DecisionInput.chooseOwned),
  (`Acorn.Host.Attempt, `Acorn.Host.DecisionInput.chooseOwned_release,
    `Acorn.Host.Released.learn),
  (`Acorn.Host.AgentAdmission, `Acorn.Handcrafted.AgentConstruction.callbacks_act,
    `Acorn.Handcrafted.AgentConstruction.callbacks),
  (`Acorn.Host.AgentAdmission, `Acorn.Handcrafted.DefaultConstruction.runPrefix_agent,
    `Acorn.Handcrafted.DefaultConstruction.runPrefix),
  (`Acorn.Timing, `Acorn.StepOrder.parse_spelled, `Acorn.StepOrder.parse),
  (`Acorn.Timing, `Acorn.StepOrder.tag_stored, `Acorn.StepOrder.tag),
  (`Acorn.Host.Cli, `Acorn.Host.Cli.value_absent, `Acorn.Host.Cli.value),
  (`Acorn.Host.Cli, `Acorn.Host.Cli.value_follows, `Acorn.Host.Cli.value),
  (`Acorn.Host.Cli, `Acorn.Host.Cli.value_missing, `Acorn.Host.Cli.value),
  (`Acorn.Host.Cli, `Acorn.Host.Cli.stepOrderValue_iff, `Acorn.Host.Cli.stepOrderValue),
  (`Acorn.Host.Cli, `Acorn.Host.Cli.stepOrder_iff, `Acorn.Host.Cli.stepOrder),
  (`Acorn.Host.Cli, `Acorn.Host.Cli.stepOrder_refused, `Acorn.Host.Cli.stepOrder),
  (`Acorn.Host.Checkpoint.Admission, `Acorn.Checkpoint.admitHeader_iff,
    `Acorn.Checkpoint.admitHeader),
  (`Acorn.Host.Checkpoint.Admission, `Acorn.Checkpoint.loadCandidate_header,
    `Acorn.Checkpoint.loadCandidate),
  (`Acorn.Host.Checkpoint.Admission, `Acorn.Checkpoint.load_candidate, `Acorn.Checkpoint.load),
  (`AcornVerif.CurrentCheckpoint, `AcornVerif.CurrentCheckpoint.saved_header,
    `Acorn.Checkpoint.saveBytes),
  (`AcornVerif.CurrentCheckpoint, `AcornVerif.CurrentCheckpoint.saved_admitted_order,
    `Acorn.Checkpoint.saveBytes),
  (`AcornVerif.CurrentCheckpoint, `AcornVerif.CurrentCheckpoint.saved_admitted_order,
    `Acorn.Checkpoint.loadCandidate),
  (`AcornVerif.CurrentCheckpoint, `AcornVerif.CurrentCheckpoint.image_roundtrip,
    `Acorn.Checkpoint.admitPayload),
  (`AcornVerif.CurrentCheckpoint, `AcornVerif.CurrentCheckpoint.image_roundtrip,
    `Acorn.Checkpoint.imagePayload),
  (`Acorn.Host.Attempt, `Acorn.Host.Attempt.complete_learned, `Acorn.Host.Attempt.complete),
  (`Acorn.Host.Runner, `Acorn.Host.runAttemptSteps_complete, `Acorn.Host.runAttemptSteps),
  (`Acorn.Host.Runner, `Acorn.Host.runReleasedSteps_complete, `Acorn.Host.runReleasedSteps),
  (`Acorn.Host.Runner, `Acorn.Host.campaignStep_attempt, `Acorn.Host.campaignStep),
  (`Acorn.Host.AgentInterface, `Acorn.Handcrafted.Agent.callbacks_act,
    `Acorn.Handcrafted.Agent.callbacks),
  (`Acorn.Host.AgentInterface, `Acorn.Handcrafted.Agent.observe_predictions,
    `Acorn.Handcrafted.Agent.observe),
  (`Acorn.Host.AgentInterface, `Acorn.Handcrafted.Agent.grid_inputs,
    `Acorn.Handcrafted.Grid.frame),
  (`AcornVerif.GridCorrespondence, `AcornVerif.GridCorrespondence.initial_eq,
    `Acorn.Handcrafted.Agent.initial),
  (`AcornVerif.GridCorrespondence, `AcornVerif.GridCorrespondence.act_eq,
    `Acorn.Handcrafted.Agent.act),
  (`AcornVerif.GridCorrespondence, `AcornVerif.GridCorrespondence.callback_eq,
    `Acorn.Handcrafted.Agent.callbacks),
  (`AcornVerif.GridCorrespondence, `AcornVerif.GridCorrespondence.restore_eq,
    `Acorn.Handcrafted.Agent.restore),
  (`Acorn.Host.Checkpoint.Frame, `Acorn.Checkpoint.roundtrip, `Acorn.Checkpoint.encode),
  (`Acorn.Host.Checkpoint.Frame, `Acorn.Checkpoint.roundtrip, `Acorn.Checkpoint.decode),
  (`Acorn.Host.Checkpoint.Admission, `Acorn.Checkpoint.load_nonmutation, `Acorn.Checkpoint.load),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.lifetime_admit, `Acorn.Checkpoint.admitLifetime),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.sum_admit, `Acorn.Checkpoint.admitSum),
  (`Acorn.Decisions, `Acorn.Decisions.bounded_admit, `Acorn.Bounded32.admit),
  (`Acorn.Decisions, `Acorn.Decisions.weight_admit, `Acorn.Weight.admit),
  (`Acorn.Decisions, `Acorn.Decisions.feature_index_admit, `Acorn.FeatIdx.admit),
  (`Acorn.Decisions, `Acorn.Decisions.action_admit, `Acorn.Features.Action.admit),
  (`Acorn.Decisions, `Acorn.Decisions.rails_admit, `Acorn.StepSizeRails.admit),
  (`Acorn.Decisions, `Acorn.Decisions.squared_admit, `Acorn.Agreement.admitSquared),
  (`Acorn.Decisions, `Acorn.Decisions.event_admit, `Acorn.Features.Event.admit),
  (`Acorn.Decisions, `Acorn.Decisions.last_admit, `Acorn.Features.admitLast),
  (`Acorn.Decisions, `Acorn.Decisions.progress_admit, `Acorn.Features.Progress.admit),
  (`Acorn.Decisions, `Acorn.Decisions.assignment_admit, `Acorn.Features.Assignment.admit),
  (`Acorn.Decisions, `Acorn.Decisions.box_position_checked, `Acorn.Host.BoxPosition.checked),
  (`Acorn.Decisions, `Acorn.Decisions.campaign_admit, `Acorn.Host.CampaignPlan.admit),
  (`Acorn.Decisions, `Acorn.Decisions.assignment_distinct, `Acorn.Features.Assignment.distinct),
  (`Acorn.Decisions, `Acorn.Decisions.harvest_key, `Acorn.Host.harvestKey),
  (`Acorn.Decisions, `Acorn.Decisions.map_index, `Acorn.Host.Viewer.mapIndex),
  (`Acorn.Decisions, `Acorn.Decisions.sse_line, `Acorn.Host.Viewer.sseLine),
  (`Acorn.Decisions, `Acorn.Decisions.checkpoint_decode, `Acorn.Checkpoint.decode),
  (`Acorn.Decisions, `Acorn.Decisions.checkpoint_save, `Acorn.Checkpoint.saveBytes),
  (`Acorn.Decisions, `Acorn.Decisions.checkpoint_load, `Acorn.Checkpoint.load),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.replay_check, `Acorn.Host.ReplayCertificate.check),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.blocked_check, `Acorn.Host.BlockedCertificate.check),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.stance_check, `Acorn.Host.StanceCertificate.check),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.replay_certified, `Acorn.Host.replayCertified),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.region_blocked, `Acorn.Host.regionBlocked),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.stance_certified, `Acorn.Host.stanceCertified),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.terrain_walkable, `Acorn.Host.walkableTile),
  (`Acorn.Decisions, `Acorn.Decisions.assignment_holds, `Acorn.Features.Assignment.holds),
  (`Acorn.Decisions, `Acorn.Decisions.assignment_same, `Acorn.Features.Assignment.same),
  (`Acorn.Decisions, `Acorn.Decisions.interest_same, `Acorn.Features.Interest.sameAssignment),
  (`Acorn.Decisions, `Acorn.Decisions.less_useful, `Acorn.Features.Lifecycle.lessUseful),
  (`Acorn.Decisions, `Acorn.Decisions.snapshot_consistent,
    `Acorn.Features.PolicySnapshot.consistent),
  (`Acorn.Decisions, `Acorn.Decisions.assignment_admit_using,
    `Acorn.Features.Assignment.admitUsing),
  (`Acorn.Decisions, `Acorn.Decisions.controller_step_raw, `Acorn.Features.Controller.stepRaw),
  (`Acorn.Decisions, `Acorn.Decisions.agent_restore, `Acorn.Handcrafted.Agent.restore),
  (`Acorn.Decisions, `Acorn.Decisions.profile_admit, `Acorn.Handcrafted.FeatureProfile.admit),
  (`Acorn.Decisions, `Acorn.Decisions.prediction_advance_raw,
    `Acorn.Handcrafted.PredictionControl.advanceRaw),
  (`Acorn.Decisions, `Acorn.Decisions.list_decode, `Acorn.Checkpoint.decodeList),
  (`Acorn.Decisions, `Acorn.Decisions.list_decode_into, `Acorn.Checkpoint.decodeListInto),
  (`Acorn.Decisions, `Acorn.Decisions.buffer_offer, `Acorn.Host.Viewer.Buffer.offer),
  (`Acorn.Decisions, `Acorn.Decisions.schema_covers, `Acorn.Host.Viewer.schemaCovers),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.demons_admit, `Acorn.Checkpoint.admitDemons),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.feature_image_admit,
    `Acorn.Features.FeatureImage.admit),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.payload_admit, `Acorn.Checkpoint.admitPayload),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.candidate_load, `Acorn.Checkpoint.loadCandidate),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.position_translate,
    `Acorn.Host.Position.translate),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.task_satisfied,
    `Acorn.Host.TaskObservation.satisfied),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.goal_satisfied, `Acorn.Host.World.goalSatisfied),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.interest_potential,
    `Acorn.Features.Interest.potential),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.precision_admit, `Acorn.Agreement.precision),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.profile_admit_accepts,
    `Acorn.Handcrafted.FeatureProfile.admit),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.checkpoint_load_accepts, `Acorn.Checkpoint.load),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.squared_admit_accepts,
    `Acorn.Agreement.admitSquared),
  (`Acorn.Decisions, `Acorn.Decisions.capture_follows, `Acorn.Host.Viewer.Capture.follows),
  (`Acorn.Decisions, `Acorn.Decisions.predicate_eval,
    `Acorn.Host.Viewer.ClockProgram.Predicate.eval),
  (`Acorn.Decisions, `Acorn.Decisions.cli_value_found, `Acorn.Host.Cli.value),
  (`Acorn.Decisions, `Acorn.Decisions.lifecycle_candidate, `Acorn.Features.Lifecycle.candidate),
  (`Acorn.Decisions, `Acorn.Decisions.assignment_identity, `Acorn.Features.Assignment.identity),
  (`Acorn.Decisions, `Acorn.Decisions.total_observe, `Acorn.Agreement.Total.observe),
  (`Acorn.Decisions, `Acorn.Decisions.world_step, `Acorn.Host.World.step),
  (`Acorn.Decisions, `Acorn.Decisions.lifecycle_mature, `Acorn.Features.Lifecycle.mature),
  (`Acorn.Decisions, `Acorn.Decisions.lifecycle_eligible, `Acorn.Features.Lifecycle.eligible),
  (`Acorn.Decisions, `Acorn.Decisions.ensemble_holds, `Acorn.Features.Ensemble.holds),
  (`Acorn.Decisions, `Acorn.Decisions.lifecycle_prefer, `Acorn.Features.Lifecycle.prefer),
  (`Acorn.Decisions, `Acorn.Decisions.assignment_potential, `Acorn.Features.Assignment.potential),
  (`Acorn.Decisions, `Acorn.Decisions.episode_end, `Acorn.Features.TemporalDecision.episodeEnd),
  (`Acorn.Decisions, `Acorn.Decisions.next_ready, `Acorn.SwiftTd.nextReady),
  (`Acorn.Decisions, `Acorn.Decisions.assignment_feature, `Acorn.Features.Assignment.feature),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.advance_actions, `Acorn.Host.World.advanceActions),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.terrain_read, `Acorn.Host.terrain),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.tile_kind, `Acorn.Host.World.tileKind),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.pay_and_act, `Acorn.Host.payAndAct),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.perform_action, `Acorn.Host.performAction),
  (`Acorn.Decisions, `Acorn.Decisions.candidate_of_weight, `Acorn.Features.candidateOfWeight),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.world_enterable, `Acorn.Host.World.enterable),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.task_observed,
    `Acorn.Host.TaskObservation.satisfied),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.exp_saturation, `Acorn.Portable.expSaturation),
  (`AcornVerif.Decisions, `AcornVerif.Decisions.rank_index, `Acorn.Host.Endurance.rankIndex),
  (`Acorn.Decisions, `Acorn.Decisions.channel_ratio, `Acorn.Agreement.Channel.ratio),
  (`Acorn.Decisions, `Acorn.Decisions.total_ratio, `Acorn.Agreement.Total.ratio),
  (`Acorn.Decisions, `Acorn.Decisions.goal_headline,
    `Acorn.Host.Viewer.GoalAchievement.State.headline),
  (`Acorn.Decisions, `Acorn.Decisions.attempt_finished, `Acorn.Host.Attempt.finished),
  (`Acorn.Decisions, `Acorn.Decisions.boundary_closing, `Acorn.Host.BoundaryDecision.closing),
  (`Acorn.Decisions, `Acorn.Decisions.checkpoint_due_at, `Acorn.Host.WritableCheckpoint.dueAt),
  (`AcornTools.Corpus.Documents, `AcornDocument.external_listed, `AcornDocument.external),
  (`Acorn.Host.Viewer.Admission, `Acorn.Host.Viewer.Admission.rejected_preserves_history,
    `Acorn.Host.Viewer.Admission.receive),
  (`Acorn.Host.Viewer.Admission, `Acorn.Host.Viewer.Admission.stored_capture,
    `Acorn.Host.Viewer.Admission.receive),
  (`Acorn.Host.Viewer.Lifecycle, `Acorn.Host.Viewer.Lifecycle.stale_preserves,
    `Acorn.Host.Viewer.Lifecycle.admit),
  (`Acorn.Host.Viewer.Lifecycle, `Acorn.Host.Viewer.Lifecycle.retire_revokes,
    `Acorn.Host.Viewer.Lifecycle.retire),
  (`Acorn.Host.Viewer.BrowserSchema, `Acorn.Host.Viewer.browserSchema_execution,
    `Acorn.Host.Viewer.coreTelemetry),
  (`Acorn.Host.Viewer.BrowserRecord, `Acorn.Host.Viewer.browserRecord_keys,
    `Acorn.Host.Viewer.browserRecordFields),
  (`Acorn.Host.Viewer.BrowserStore, `Acorn.Host.Viewer.browserColumns_live,
    `Acorn.Host.Viewer.browserColumns),
  (`NativeApp.MutationAudit, `NativeApp.AuditArm.incumbent_profile,
    `NativeApp.AuditArm.construction),
  (`AcornVerif.CurrentCertificates, `AcornVerif.CurrentCertificates.replay_feasible,
    `Acorn.Host.replayCertified),
  (`AcornVerif.CurrentCertificates, `AcornVerif.CurrentCertificates.blocked_outside,
    `Acorn.Host.regionBlocked),
  (`AcornVerif.CurrentCertificates, `AcornVerif.CurrentCertificates.stance_harvest,
    `Acorn.Host.stanceCertified)
]

/-- Required native entry dependencies after proof erasure. These are routing
obligations; the IR graph alone does not prove control-flow or argument semantics.
Erased ANSI and checksum parameters select the compiler's reduced-arity owners. -/
def entryUses : Array (Name × Array Name) := #[
  (`NativeApp.Main, #[`NativeApp.streamingOptions, `Acorn.Host.Viewer.runNativeCampaign,
    `Acorn.Host.StopFlag.withCommands._redArg,
    `Acorn.Handcrafted.Agent.callbacks, `Acorn.Handcrafted.AgentConstruction.callbacks,
    `Acorn.Handcrafted.AgentConstruction.runCampaign,
    `Acorn.Checkpoint.Store.hooks,
    `Acorn.Host.runAnsi._redArg, `Acorn.Host.agentChecksum._redArg, `NativeApp.runMutationAudit,
    `NativeApp.AuditArm.construction]),
  (`NativeApp.Viewer, #[`NativeApp.runViewer, `Acorn.Host.Viewer.ViewerOptions.decode,
    `Acorn.Host.Viewer.Supervisor.new, `Acorn.Host.Viewer.Supervisor.step]),
  (`NativeApp.BrowserKernel, #[`Acorn.Host.Viewer.browserKernelJavascript]),
  (`Acorn.SwiftTdDriver, #[`Acorn.SwiftTdDriver.execute]),
  (`Acorn.FeatureDriver, #[`Acorn.FeatureDriver.execute]),
  (`Acorn.ControlDriver, #[`Acorn.ControlDriver.execute]),
  (`Acorn.TemporalDriver, #[`Acorn.TemporalDriver.execute]),
  (`Acorn.AgentDriver, #[`Acorn.AgentDriver.execute]),
  (`Acorn.WorldDriver, #[`Acorn.WorldDriver.execute]),
  (`Acorn.Host.CheckpointDriver, #[`Acorn.Host.CheckpointDriver.dispatch]),
  (`Acorn.Host.CertificateDriver, #[`Acorn.Host.CertificateDriver.execute,
    `Acorn.Host.replayCertified, `Acorn.Host.regionBlocked, `Acorn.Host.stanceCertified]),
  (`AcornTools.Boundary.Main, #[`AcornBoundaryAudit.command]),
  (`AcornTools.TheoremCount, #[`AcornTheoremCount.inventory]),
  (`AcornTools.Native.Audit, #[`AcornNativeAudit.audit]),
  (`AcornTools.OwnershipAudit, #[`AcornOwnershipAudit.compiled]),
  (`AcornTools.Corpus.Main, #[`AcornCorpus.check]),
  (`AcornTools.Gate, #[`AcornGate.verify])
]

end AcornOwnership
