/-
Copyright (c) 2026 acorn contributors. All rights reserved.
Released under the MIT license as described in the repository LICENSE.
Authors: acorn contributors
-/
import Init

/-! # Reviewed native call routes

These compiler-symbol sequences retain the native boundary's existing routing
obligations. They detect replacement drift, not correctness of the generated C.
The owning Lean definitions and their proofs establish the semantic contracts.
-/
namespace AcornNativeRoutes

/-- Module, compiled function, and ordered calls of each reviewed native route. -/
def routes : Array (String × String × Array String) := #[
  ("Host/Control", "lp_acorn___private_Acorn_Host_Control_0__Acorn_Host_closeCommandSource", #["lean_io_cancel", "lean_io_process_child_try_wait", "lean_io_process_child_kill", "lean_io_process_child_wait"]),
  ("Host/Control", "lp_acorn___private_Acorn_Host_Control_0__Acorn_Host_ClosedCommandSource_join", #["lean_task_get_own"]),
  ("Host/Control", "lp_acorn_Acorn_Host_StopFlag_withCommands___redArg___lam__1", #["lp_acorn___private_Acorn_Host_Control_0__Acorn_Host_closeCommandSource", "lp_acorn___private_Acorn_Host_Control_0__Acorn_Host_ClosedCommandSource_join"]),
  ("Host/Control", "lp_acorn_Acorn_Host_StopFlag_withCommands___redArg", #["lean_io_process_spawn", "lean_io_as_task", "lp_acorn_Acorn_Host_StopFlag_withCommands___redArg___lam__1", "lp_acorn_Acorn_Host_StopFlag_withCommands___redArg___lam__1"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary32_ofUInt64", #["lean_uint64_to_float32", "lean_float32_to_bits"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary32_add", #["lean_float32_of_bits", "lean_float32_of_bits", "lean_float32_add", "lean_float32_to_bits"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary32_sub", #["lean_float32_of_bits", "lean_float32_of_bits", "lean_float32_sub", "lean_float32_to_bits"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary32_mul", #["lean_float32_of_bits", "lean_float32_of_bits", "lean_float32_mul", "lean_float32_to_bits"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary32_div", #["lean_float32_of_bits", "lean_float32_of_bits", "lean_float32_div", "lean_float32_to_bits"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary64_ofUInt64", #["lean_uint64_to_float", "lean_float_to_bits"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary64_add", #["lean_float_of_bits", "lean_float_of_bits", "lean_float_add", "lean_float_to_bits"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary64_sub", #["lean_float_of_bits", "lean_float_of_bits", "lean_float_sub", "lean_float_to_bits"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary64_mul", #["lean_float_of_bits", "lean_float_of_bits", "lean_float_mul", "lean_float_to_bits"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary64_div", #["lean_float_of_bits", "lean_float_of_bits", "lean_float_div", "lean_float_to_bits"]),
  ("Conversion", "lp_acorn_Acorn_Conversion_toI32", #["lp_acorn_Acorn_Conversion_toI32Word", "lean_int32_to_int"]),
  ("Conversion", "lp_acorn_Acorn_Conversion_signedCast", #["lp_acorn_Acorn_Binary64_isNaN", "lp_acorn_Acorn_Binary64_magnitude", "lp_acorn_Acorn_Conversion_trunc64", "lp_acorn_Acorn_Conversion_clampInt"]),
  ("Conversion", "lp_acorn_Acorn_Conversion_ofInt", #["lean_uint64_to_float", "lean_float_to_bits"]),
  ("Rng", "lp_acorn_Acorn_Rng_Fraction53_toBinary64", #["lp_acorn_Acorn_Binary64_ofUInt64", "lp_acorn_Acorn_Binary64_mul"]),
  ("Rng", "lp_acorn_Acorn_Rng_Xoshiro256_nextFraction", #["lp_acorn_Acorn_Rng_Xoshiro256_next", "lp_acorn_Acorn_Rng_Fraction53_ofWord"]),
  ("Rng", "lp_acorn_Acorn_Rng_Xoshiro256_nextF64", #["lp_acorn_Acorn_Rng_Xoshiro256_nextFraction", "lp_acorn_Acorn_Rng_Fraction53_toBinary64"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary64_hornerStep", #["lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_add"]),
  ("Arithmetic", "lp_acorn_Acorn_Bounded32_addProjected", #["lp_acorn_Acorn_Binary32_add", "lp_acorn_Acorn_Interval32_saturate"]),
  ("Average", "lp_acorn_Acorn_AverageRewardTracker_observe", #["lp_acorn_Acorn_RewardRate_project", "lp_acorn_Acorn_Binary32_sub", "lp_acorn_Acorn_Binary32_mul", "lp_acorn_Acorn_Binary32_add", "lp_acorn_Acorn_RewardRate_project"]),
  ("Portable", "lp_acorn_Acorn_Portable_expScaleWord", #["lp_acorn_Acorn_Portable_powerOfTwoWord", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Conversion_narrow"]),
  ("Portable", "lp_acorn_Acorn_Portable_expScale", #["lp_acorn_Acorn_Portable_powerOfTwo", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Conversion_narrow"]),
  ("Portable", "lp_acorn_Acorn_Portable_exp", #["lp_acorn_Acorn_Binary32_isNaN", "lp_acorn_Acorn_Binary32_less", "lp_acorn_Acorn_Binary32_less", "lp_acorn_Acorn_Conversion_widen", "lp_acorn_Acorn_Portable_expExponent", "lp_acorn_Acorn_Portable_expRemainder", "lp_acorn_Acorn_Portable_expSeries", "lp_acorn_Acorn_Portable_expScaleWord"]),
  ("Portable", "lp_acorn_Acorn_Portable_expReduceWord", #["lp_acorn_Acorn_Portable_expExponent", "lp_acorn_Acorn_Portable_expRemainder"]),
  ("Portable", "lp_acorn_Acorn_Portable_pow", #["lp_acorn_Acorn_Conversion_widen", "lp_acorn_Acorn_Portable_powLoopWord", "lp_acorn_Acorn_Conversion_narrow"]),
  ("Portable", "lp_acorn_Acorn_Portable_powLoop", #["lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_mul"]),
  ("Portable", "lp_acorn_Acorn_Portable_powLoopWord", #["lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_mul"]),
  ("State", "lp_acorn_Acorn_Weight_project", #["lp_acorn_Acorn_Bounded32_projectSymmetric"]),
  ("State", "lp_acorn_Acorn_Prediction_project", #["lp_acorn_Acorn_Discount_predictionRange", "lp_acorn_Acorn_Interval32_saturate"]),
  ("State", "lp_acorn_Acorn_LogStepSize_project", #["lp_acorn_Acorn_Interval32_saturate"]),
  ("State", "lp_acorn_Acorn_NumericState_writeWeight___redArg", #["lp_acorn_Acorn_Weight_project"]),
  ("State", "lp_acorn_Acorn_NumericState_writeBetaValue___redArg", #["lp_acorn_Acorn_Portable_exp"]),
  ("State", "lp_acorn_Acorn_NumericState_writeBeta___redArg", #["lp_acorn_Acorn_Interval32_saturate", "lp_acorn_Acorn_NumericState_writeBetaValue___redArg"]),
  ("State", "lp_acorn_Acorn_LogStepSize_alphaAfter___redArg", #["lp_acorn_Acorn_Portable_exp"]),
  ("SwiftTd", "lp_acorn_Acorn_NumericState_restoreLogStepSizes", #["lp_acorn_Acorn_SwiftTd_restorePrefix___redArg", "lp_acorn___private_Init_Data_Array_Basic_0__Array_mapMUnsafe_map___at___00Acorn_NumericState_restoreLogStepSizes_spec__0___redArg"]),
  ("SwiftTd", "lp_acorn___private_Init_Data_Array_Basic_0__Array_mapMUnsafe_map___at___00Acorn_NumericState_restoreLogStepSizes_spec__0___redArg", #["lp_acorn_Acorn_Portable_exp"]),
  ("Conversion", "lp_acorn_Acorn_Conversion_widenNaN", #["lean_float32_of_bits", "lean_float32_to_float", "lean_float_to_bits"]),
  ("Conversion", "lp_acorn_Acorn_Conversion_narrowNaN", #["lean_float_of_bits", "lean_float_to_float32", "lean_float32_to_bits"]),
  ("Conversion", "lp_acorn_Acorn_Conversion_widen", #["lp_acorn_Acorn_Conversion_widenSign", "lp_acorn_Acorn_Conversion_widenFraction", "lp_acorn_Acorn_Conversion_widenSubnormalFraction", "lp_acorn_Acorn_Conversion_widenNaN"]),
  ("Conversion", "lp_acorn_Acorn_Conversion_narrow", #["lp_acorn_Acorn_Conversion_narrowSign", "lp_acorn_Acorn_Conversion_subnormalFractionWord", "lp_acorn_Acorn_Conversion_normalMagnitude", "lp_acorn_Acorn_Conversion_narrowNaN"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary32_sumFrom", #["lp_acorn_List_foldl___at___00Acorn_Binary32_sumFrom_spec__0"]),
  ("Arithmetic", "lp_acorn_List_foldl___at___00Acorn_Binary32_sumFrom_spec__0", #["lp_acorn_Acorn_Binary32_add"]),
  ("Arithmetic", "lp_acorn_Acorn_Binary64_hornerFrom", #["lp_acorn_List_foldl___at___00Acorn_Binary64_hornerFrom_spec__0"]),
  ("Arithmetic", "lp_acorn_List_foldl___at___00Acorn_Binary64_hornerFrom_spec__0", #["lp_acorn_Acorn_Binary64_hornerStep"]),
  ("Portable", "lp_acorn_Acorn_Portable_expSeries", #["lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep"]),
  ("Portable", "lp_acorn_Acorn_Portable_ln", #["lp_acorn_Acorn_Binary32_isNaN", "lp_acorn_Acorn_Binary32_less", "lp_acorn_Acorn_Binary64_sub", "lp_acorn_Acorn_Binary64_add", "lp_acorn_Acorn_Binary64_div", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Portable_lnSeries", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_add", "lp_acorn_Acorn_Binary64_add", "lp_acorn_Acorn_Conversion_narrow", "lp_acorn_Acorn_Binary64_add", "lp_acorn_Acorn_Binary32_magnitudeEq", "lp_acorn_Acorn_Binary32_magnitudeEq", "lp_acorn_Acorn_Conversion_widen", "lp_acorn_Acorn_Portable_logarithmExponent", "lp_acorn_Acorn_Conversion_ofI32Word", "lp_acorn_Acorn_Binary64_less", "lp_acorn_Acorn_Binary64_mul"]),
  ("Portable", "lp_acorn_Acorn_Portable_lnSeries", #["lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep", "lp_acorn_Acorn_Binary64_hornerStep"]),
  ("SwiftTd", "lp_acorn_Acorn_NumericState_firstLoopElement___redArg", #["lp_acorn_Acorn_Binary32_mul", "lp_acorn_Acorn_Binary32_mul", "lp_acorn_Acorn_Binary32_sub", "lp_acorn_Acorn_Binary32_add", "lp_acorn_Acorn_Weight_project", "lp_acorn_Acorn_Binary32_numericallyEqual", "lp_acorn_Acorn_StepSizeRails_initial", "lp_acorn_Acorn_Portable_exp", "lp_acorn_Acorn_Binary32_lessOrEqual", "lp_acorn_Acorn_Binary32_div", "lp_acorn_Acorn_Interval32_saturate", "lp_acorn_Acorn_LogStepSize_alphaAfter___redArg"]),
  ("SwiftTd", "lp_acorn_Acorn_NumericState_secondLoopElementAt___redArg", #["lp_acorn_Acorn_Binary32_isZero", "lp_acorn_Acorn_StepSizeRails_decay", "lp_acorn_Acorn_Binary32_add", "lp_acorn_Acorn_Interval32_saturate", "lp_acorn_Acorn_NumericState_writeBetaValue___redArg", "lp_acorn_Acorn_Binary32_add", "lp_acorn_Acorn_Binary32_mul"]),
  ("SwiftTd", "lp_acorn_Acorn_NumericState_secondLoopElement___redArg", #["lp_acorn_Acorn_Config_eta", "lp_acorn_Acorn_Binary32_div", "lp_acorn_Acorn_Binary32_sub", "lp_acorn_Acorn_Portable_exp", "lp_acorn_Acorn_NumericState_secondLoopElementAt___redArg"]),
  ("SwiftTd", "lp_acorn_Acorn_NumericState_learnFirstLoopGo___redArg", #["lp_acorn_Acorn_NumericState_firstLoopElement___redArg", "lp_acorn_Acorn_NumericState_clearFeatureRegisters___redArg", "lp_acorn_Acorn_SwiftTd_swapRemove___redArg"]),
  ("SwiftTd", "lp_acorn_Acorn_NumericState_step___redArg", #["lp_acorn_Acorn_NumericState_linearPrediction___redArg", "lp_acorn_Acorn_Binary32_mul", "lp_acorn_Acorn_Binary32_add", "lp_acorn_Acorn_Binary32_sub", "lp_acorn_Acorn_NumericState_learnFirstLoop___redArg", "lp_acorn_Acorn_NumericState_learnSecondLoop___redArg"]),
  ("SwiftTd", "lp_acorn_Acorn_SwiftTd_Entry_apply", #["lp_acorn_Acorn_NumericState_learnFirstLoop___redArg", "lp_acorn_Acorn_NumericState_learnSecondLoop___redArg", "lp_acorn_Acorn_NumericState_step___redArg", "lp_acorn_Acorn_NumericState_beginTrajectory", "lp_acorn_Acorn_NumericState_terminalStep", "lp_acorn_Acorn_NumericState_planStep___redArg", "lp_acorn_Acorn_NumericState_retireIndex", "lp_acorn_Acorn_NumericState_restoreWeights", "lp_acorn_Acorn_NumericState_restoreLogStepSizes", "lp_acorn_Acorn_NumericState_installRestored", "lp_acorn_Acorn_NumericState_clearTransient___redArg", "lp_acorn_Acorn_NumericState_releaseEligible"]),
  ("SwiftTdDriver", "lp_acorn_Acorn_SwiftTdDriver_run", #["lp_acorn_Acorn_FeatIdx_fromHash", "lp_acorn_Acorn_SwiftTd_Entry_apply"]),
  ("SwiftTdDriver", "lp_acorn_Acorn_SwiftTdDriver_execute", #["lp_acorn_Acorn_NumericState_initial", "lp_acorn_Acorn_SwiftTdDriver_run"]),
  ("SwiftTd", "lp_acorn_Acorn_NumericState_learnSecondLoop___redArg", #["lp_acorn_List_mapTR_loop___at___00Acorn_NumericState_learnSecondLoop_spec__0", "lp_acorn_List_foldl___at___00Acorn_Binary32_sumFrom_spec__0", "lp_acorn_Acorn_Config_eta", "lp_acorn_Acorn_Binary32_less", "lp_acorn_List_foldl___at___00Acorn_NumericState_learnSecondLoop_spec__1", "lp_acorn_Acorn_Binary32_div", "lp_acorn_Acorn_Binary32_sub", "lp_acorn_Acorn_NumericState_learnSecondLoopGo___redArg"]),
  ("SwiftTd", "lp_acorn_Acorn_NumericState_learnSecondLoopGo___redArg", #["lp_acorn_Acorn_NumericState_secondLoopElementAt___redArg"]),
  ("SwiftTd", "lp_acorn_Acorn_NumericState_planStep___redArg", #["lp_acorn_Acorn_NumericState_linearPrediction___redArg", "lp_acorn_List_mapTR_loop___at___00Acorn_NumericState_learnSecondLoop_spec__0", "lp_acorn_List_foldl___at___00Acorn_Binary32_sumFrom_spec__0", "lp_acorn_Acorn_Config_eta", "lp_acorn_Acorn_Binary32_less", "lp_acorn_Acorn_Binary32_div", "lp_acorn_Acorn_NumericState_planWeightsGo___redArg"]),
  ("SwiftTd", "lp_acorn_Acorn_NumericState_planWeightsGo___redArg", #["lp_acorn_Acorn_Binary32_mul", "lp_acorn_Acorn_Binary32_mul", "lp_acorn_Acorn_Binary32_add", "lp_acorn_Acorn_NumericState_writeWeight___redArg"]),
  ("Features", "lp_acorn_Acorn_Features_encode", #["lp_acorn_Acorn_Features_Bank_activations", "lp_acorn_Acorn_Features_encodeWith"]),
  ("Features", "lp_acorn_Acorn_Features_encodeWith", #["lp_acorn_Acorn_Features_rawEncodeWith", "lp_acorn_Acorn_Features_unique"]),
  ("FeatureLifecycle", "lp_acorn_Acorn_Features_Lifecycle_test", #["lp_acorn_Acorn_Features_Lifecycle_score___redArg", "lp_acorn_Acorn_Features_Lifecycle_accrued", "lp_acorn_Acorn_Features_Tester_due", "lp_acorn_Acorn_Features_Tester_remainder", "lp_acorn_Acorn_Features_Lifecycle_withCredit___redArg", "lp_acorn_Acorn_Features_Lifecycle_replaceDue"]),
  ("FeatureLifecycle", "lp_acorn_Acorn_Features_Lifecycle_replaceDue", #["lp_acorn_Acorn_Features_Lifecycle_candidate", "lp_acorn_Acorn_Features_Lifecycle_replace", "lp_acorn_Acorn_Features_Lifecycle_replaceDue"]),
  ("FeatureLifecycle", "lp_acorn_Acorn_Features_Lifecycle_replace", #["lp_acorn_Acorn_Features_Representation_replace___redArg", "lp_acorn_Acorn_Features_unitFeature", "lp_acorn_Acorn_Features_Ensemble_retire"]),
  ("FeatureConsumers", "lp_acorn_Acorn_Features_Skill_retire___redArg", #["lp_acorn_Acorn_Features_Controller_retire___redArg", "lp_acorn_Acorn_Features_Model_retire___redArg", "lp_acorn_Acorn_Features_OptionQuestions_retire___redArg"]),
  ("OffPolicy", "lp_acorn_Acorn_Features_OptionQuestions_retire___redArg", #["lp_acorn_Acorn_Features_GradientBank_retire___redArg", "lp_acorn_Acorn_Features_Preceding_retire"]),
  ("FeatureHistory", "lp_acorn_Acorn_Features_Representation_replace___redArg", #["lp_acorn_Acorn_Features_Progress_replace___redArg", "lp_acorn_Acorn_Features_Bank_replace___redArg"]),
  ("FeatureConsumers", "lp_acorn_Acorn_Features_Managed_retire", #["lp_acorn_Acorn_Features_Managed_apply___redArg"]),
  ("FeatureRefresh", "lp_acorn_Acorn_Features_FreeDispatch_refreshRanked___redArg", #["lp_acorn_Acorn_Features_DemonBank_rankingWeights___redArg", "lp_acorn_Acorn_Features_rankAssignments"]),
  ("FeatureDriver", "lp_acorn_Acorn_FeatureDriver_execute", #["lp_acorn_Acorn_Features_Representation_initial", "lp_acorn_Acorn_Features_Ensemble_initial", "lp_acorn_Acorn_Handcrafted_FeatureProfile_encode", "lp_acorn_Acorn_Handcrafted_observationPatch", "lp_acorn_Acorn_Features_Bank_activations", "lp_acorn_Acorn_Features_FeatureRuntime_retire___redArg", "lp_acorn_Acorn_Features_FeatureRuntime_refreshAtFree___redArg", "lp_acorn_Acorn_Features_Bank_checksum___redArg"]),
  ("Handcrafted/Observation", "lp_acorn_Acorn_Handcrafted_predictionBucket", #["lp_acorn_Acorn_Binary32_div", "lp_acorn_Acorn_Binary32_saturate", "lp_acorn_Acorn_Binary32_mul", "lean_float32_of_bits", "floorf", "lean_float32_to_uint8"]),
  ("Sarsa", "lp_acorn_Acorn_Features_Controller_step", #["lp_acorn_Acorn_Features_Controller_predictAll___redArg", "lp_acorn_Acorn_Features_Controller_valuesStep"]),
  ("Demon", "lp_acorn_Acorn_Features_DemonBank_step___redArg", #["lp_acorn_Acorn_NumericState_step___redArg", "lp_acorn_Acorn_Prediction_project"]),
  ("ControlDriver", "lp_acorn_Acorn_ControlDriver_execute", #["lp_acorn_Acorn_Handcrafted_PredictionControl_initial", "lp_acorn_Acorn_Handcrafted_PredictionControl_encode___redArg", "lp_acorn_Acorn_Features_Controller_snapshot___redArg", "lp_acorn_Acorn_Features_PolicySnapshot_draw", "lp_acorn_Acorn_Handcrafted_PredictionControl_advance"]),
  ("Sarsa", "lp_acorn_Acorn_Features_Controller_valuesStep", #["lp_acorn_Acorn_Binary32_mul", "lp_acorn_Acorn_Binary32_add", "lp_acorn_Acorn_Binary32_sub", "lp_acorn_Acorn_Features_Controller_creditStep"]),
  ("Options", "lp_acorn_Acorn_Features_Skill_beginOption___redArg", #["lp_acorn_Acorn_Features_Controller_clear___redArg", "lp_acorn_Acorn_Features_ConsumerRate_resolve", "lp_acorn_Acorn_Features_Controller_snapshot___redArg"]),
  ("Options", "lp_acorn_Acorn_Features_Skill_optionStep___redArg", #["lp_acorn_Acorn_Features_PolicySnapshot_drawPersistent", "lp_acorn_Acorn_Features_Criterion_center", "lp_acorn_Acorn_Features_shapedCumulant", "lp_acorn_Acorn_Features_Controller_persistentStep", "lp_acorn_Acorn_Features_ModelAge_advance"]),
  ("Options", "lp_acorn_Acorn_Features_Skill_terminateOption___redArg", #["lp_acorn_Acorn_Features_Criterion_center", "lp_acorn_Acorn_Features_Interest_stoppingValue___redArg", "lp_acorn_Acorn_Features_terminalCumulant", "lp_acorn_Acorn_Features_Controller_terminal___redArg"]),
  ("Exploration", "lp_acorn_Acorn_Features_beginExploration", #["lp_acorn_Acorn_Rng_Xoshiro256_nextF64", "lp_acorn_Acorn_Conversion_widen", "lp_acorn_Acorn_Binary64_less", "lp_acorn_Acorn_Rng_Xoshiro256_nextF64", "lp_acorn_Acorn_Features_uniformAction"]),
  ("Exploration", "lp_acorn_Acorn_Features_Controller_persistentStep", #["lp_acorn_Acorn_Portable_pow", "lp_acorn_Acorn_Portable_pow", "lp_acorn_Acorn_Features_Controller_valuesStep"]),
  ("Exploration", "lp_acorn_Acorn_Features_durationRemaining", #["lp_acorn_Acorn_Features_durationWord"]),
  ("Exploration", "lp_acorn_Acorn_Features_durationWord", #["lp_acorn_Acorn_Features_durationCountWord"]),
  ("Exploration", "lp_acorn_Acorn_Features_durationCountWord", #["lp_acorn_Acorn_Binary64_sub", "lp_acorn_Acorn_Binary64_div", "lp_acorn_Acorn_Binary64_less", "lp_acorn_Acorn_Conversion_cappedTrunc128"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_atBoundary", #["lp_acorn_Acorn_Handcrafted_TemporalControl_refreshFree", "lp_acorn_Acorn_Handcrafted_TemporalControl_planFree___redArg", "lp_acorn_Acorn_Handcrafted_TemporalControl_drawMeta___redArg", "lp_acorn_Acorn_Features_PolicyDecision_continuation___redArg", "lp_acorn_Acorn_Handcrafted_TemporalControl_closeOption___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_step", #["lp_acorn_Acorn_Handcrafted_spatialPotentials", "lp_acorn_Acorn_Handcrafted_TemporalControl_select", "lp_acorn_Acorn_Features_modelOperations", "lp_acorn_Acorn_Handcrafted_TemporalControl_followOptions", "lp_acorn_Acorn_Handcrafted_TemporalControl_finish"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_followOptions", #["lp_acorn_Acorn_Handcrafted_FeatureProfile_usesHierarchy", "lp_acorn_Acorn_Handcrafted_TemporalControl_stoppingEstimate___redArg", "lp_acorn_Acorn_Handcrafted_TemporalControl_skillRate___redArg", "lp_acorn_Acorn_Handcrafted_TemporalControl_activeSlot___redArg", "lp_acorn___private_Init_Data_Array_Basic_0__Array_mapFinIdxMUnsafe_map___at___00Acorn_Handcrafted_TemporalControl_followOptions_spec__1___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_stoppingEstimate___redArg", #["lp_acorn_Acorn_Handcrafted_TemporalControl_metaRate___redArg", "lp_acorn_Acorn_Features_comparisonValue", "lp_acorn_Acorn_Features_comparisonValue"]),
  ("Handcrafted/TemporalControl", "lp_acorn___private_Init_Data_Array_Basic_0__Array_mapFinIdxMUnsafe_map___at___00Acorn_Handcrafted_TemporalControl_followOptions_spec__1___redArg", #["lp_acorn_Acorn_Handcrafted_followSlot"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_followSlot", #["lp_acorn_Acorn_Features_Interest_potential", "lp_acorn_Acorn_Features_Skill_followTemporal___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_closeOption___redArg", #["lp_acorn_Acorn_Handcrafted_TemporalControl_valueFunction___redArg", "lp_acorn_Acorn_Features_detachedUpdate___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_closeOption___redArg___lam__0", #["lp_acorn_Acorn_Features_Skill_endTemporal___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_dispatchMeta", #["lp_acorn_Acorn_Handcrafted_TemporalControl_learnMeta___redArg", "lp_acorn_Acorn_Handcrafted_TemporalControl_choosePrimitive___redArg", "lp_acorn_Acorn_Features_Interest_potential", "lp_acorn_Acorn_Handcrafted_TemporalControl_valueFunction___redArg", "lp_acorn_Acorn_Handcrafted_TemporalControl_skillRate___redArg", "lp_acorn_Acorn_Features_detachedUpdate___redArg", "lp_acorn_Acorn_Handcrafted_TemporalControl_stepOption___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_dispatchMeta___lam__0", #["lp_acorn_Acorn_Features_comparisonValue", "lp_acorn_Acorn_Features_Skill_settleTemporal___redArg", "lp_acorn_Acorn_Features_Skill_beginTemporal___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_stepOption___redArg", #["lp_acorn_Acorn_Features_detachedUpdate___redArg", "lp_acorn_Acorn_Features_Occupancy_afterOption___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_choosePrimitive___redArg", #["lp_acorn_Acorn_Features_PolicySnapshot_drawPersistent", "lp_acorn_Acorn_Features_Occupancy_afterPrimitive___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_serve___redArg", #["lp_acorn_Acorn_Features_ExploratoryRun_serve___redArg", "lp_acorn_Acorn_Handcrafted_TemporalControl_interrupt___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_interrupt___redArg", #["lp_acorn_Acorn_Features_OptionActivation_following___redArg", "lp_acorn_Acorn_Handcrafted_TemporalControl_withSkill___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_stepOption___redArg___lam__0", #["lp_acorn_Acorn_Features_Skill_stepTemporal___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_learnMeta___redArg", #["lp_acorn_Acorn_Features_Controller_policyStep"]),
  ("Temporal", "lp_acorn_Acorn_Features_Skill_settleTemporal___redArg", #["lp_acorn_Acorn_Features_Skill_settleFollowing___redArg"]),
  ("Temporal", "lp_acorn_Acorn_Features_Skill_settleFollowing___redArg", #["lp_acorn_Acorn_Features_Following_activation", "lp_acorn_Acorn_Features_Skill_decideOption___redArg", "lp_acorn_Acorn_Features_Criterion_center", "lp_acorn_Acorn_Features_shapedCumulant", "lp_acorn_Acorn_Features_Controller_backupError___redArg", "lp_acorn_Acorn_Features_Controller_stopStep___redArg", "lp_acorn_Acorn_Features_Skill_stopFollowing___redArg"]),
  ("Temporal", "lp_acorn_Acorn_Features_Skill_followTemporal___redArg", #["lp_acorn_Acorn_Features_Skill_startFollowing___redArg", "lp_acorn_Acorn_Features_Following_activation", "lp_acorn_Acorn_Features_Skill_decideOption___redArg", "lp_acorn_Acorn_Features_PolicySnapshot_consistent", "lp_acorn_Acorn_Features_ModelAge_advance", "lp_acorn_Acorn_Features_Criterion_center", "lp_acorn_Acorn_Features_shapedCumulant", "lp_acorn_Acorn_Features_Controller_backupStep", "lp_acorn_Acorn_Features_Skill_stopFollowing___redArg", "lp_acorn_Acorn_Features_Skill_startFollowing___redArg"]),
  ("Temporal", "lp_acorn_Acorn_Features_Skill_startFollowing___redArg", #["lp_acorn_Acorn_Features_ConsumerRate_resolve", "lp_acorn_Acorn_Features_Controller_snapshot___redArg", "lp_acorn_Acorn_Features_PolicySnapshot_consistent", "lp_acorn_Acorn_Features_Controller_startStep"]),
  ("Temporal", "lp_acorn_Acorn_Features_Skill_stopFollowing___redArg", #["lp_acorn_Acorn_Features_Criterion_center", "lp_acorn_Acorn_Features_Interest_stoppingValue___redArg", "lp_acorn_Acorn_Features_terminalCumulant", "lp_acorn_Acorn_Binary32_sub", "lp_acorn_Acorn_Features_Controller_stopStep___redArg"]),
  ("Sarsa", "lp_acorn_Acorn_Features_Controller_startStep", #["lp_acorn_Acorn_Features_Controller_release___redArg", "lp_acorn_Acorn_Features_Controller_creditStep"]),
  ("Sarsa", "lp_acorn_Acorn_Features_Controller_release___redArg", #["lp_acorn___private_Init_Data_Array_Basic_0__Array_mapMUnsafe_map___at___00Acorn_Features_Controller_release_spec__0"]),
  ("Sarsa", "lp_acorn___private_Init_Data_Array_Basic_0__Array_mapMUnsafe_map___at___00Acorn_Features_Controller_release_spec__0", #["lp_acorn_Acorn_Features_Managed_apply___redArg"]),
  ("Policy", "lp_acorn_Acorn_Features_PolicySnapshot_consistent", #["lp_acorn_Acorn_Features_PolicySnapshot_probabilities"]),
  ("Policy", "lp_acorn_Acorn_Features_Controller_backupStep", #["lp_acorn_Acorn_Features_Controller_backupError___redArg", "lp_acorn_Acorn_Features_Controller_traceDecay___redArg", "lp_acorn_Acorn_Features_PolicySnapshot_mass", "lp_acorn_Acorn_Binary32_mul", "lp_acorn_Acorn_Features_Controller_creditStep"]),
  ("Policy", "lp_acorn_Acorn_Features_Controller_backupError___redArg", #["lp_acorn_Acorn_ValueRule_gamma", "lp_acorn_Acorn_Features_PolicySnapshot_expected", "lp_acorn_Acorn_Binary32_mul", "lp_acorn_Acorn_Binary32_add", "lp_acorn_Acorn_Binary32_sub"]),
  ("Policy", "lp_acorn_Acorn_Features_PolicySnapshot_mass", #["lp_acorn_Acorn_Features_PolicySnapshot_probabilities", "lp_acorn_Acorn_SwiftTd_ExploreRate_project"]),
  ("Sarsa", "lp_acorn_Acorn_Features_Controller_creditStep", #["lp_acorn_Acorn_Features_detachedUpdate___redArg", "lp_acorn___private_Init_Data_Array_Basic_0__Array_mapFinIdxMUnsafe_map___at___00Acorn_Features_Controller_creditStep_spec__0___redArg"]),
  ("Sarsa", "lp_acorn_Acorn_Features_Controller_creditStep___lam__0", #["lp_acorn_Acorn_Features_Managed_credit", "lp_acorn_Acorn_NumericState_learnSecondLoop___redArg"]),
  ("Sarsa", "lp_acorn___private_Init_Data_Array_Basic_0__Array_mapFinIdxMUnsafe_map___at___00Acorn_Features_Controller_creditStep_spec__0___redArg", #["lp_acorn_Acorn_Features_Managed_credit"]),
  ("FeatureConsumers", "lp_acorn_Acorn_Features_detachedUpdate___redArg", #["lp_acorn_Acorn_Features_takeOut___redArg", "lean_apply_1"]),
  ("Sarsa", "lp_acorn_Acorn_Features_Controller_stopStep___redArg", #["lp_acorn___private_Init_Data_Array_Basic_0__Array_mapMUnsafe_map___at___00Acorn_Features_Controller_stopStep_spec__0"]),
  ("Sarsa", "lp_acorn___private_Init_Data_Array_Basic_0__Array_mapMUnsafe_map___at___00Acorn_Features_Controller_stopStep_spec__0", #["lp_acorn_Acorn_Features_Managed_credit", "lp_acorn_Acorn_Features_Managed_apply___redArg"]),
  ("Models", "lp_acorn_Acorn_Features_Model_restart", #["lp_acorn_Acorn_Features_modelInput", "lp_acorn_Acorn_Features_Managed_restartTrajectory"]),
  ("Models", "lp_acorn_Acorn_Features_Model_stop___redArg", #["lp_acorn_Acorn_Features_Transition_outcome", "lp_acorn_Acorn_Features_Managed_stopTrajectory", "lp_acorn_Acorn_Features_Transition_stop"]),
  ("Models", "lp_acorn_Acorn_Features_Managed_restartTrajectory", #["lp_acorn_Acorn_Features_Managed_apply___redArg", "lp_acorn_Acorn_Features_Managed_apply___redArg"]),
  ("Models", "lp_acorn_Acorn_Features_Managed_stopTrajectory", #["lp_acorn_Acorn_Binary32_sub", "lp_acorn_Acorn_Features_Managed_apply___redArg", "lp_acorn_Acorn_Features_Managed_apply___redArg"]),
  ("SwiftTd", "lp_acorn_Acorn_NumericState_releaseEligible", #["lp_acorn___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00Acorn_NumericState_releaseEligible_spec__0___redArg"]),
  ("SwiftTd", "lp_acorn___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00Acorn_NumericState_releaseEligible_spec__0___redArg", #["lp_acorn_Acorn_NumericState_clearFeatureRegisters___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_finish", #["lp_acorn_Acorn_Handcrafted_evaluateCumulants", "lp_acorn_Acorn_Features_TemporalDecision_episodeEnd", "lp_acorn_Acorn_Lifetime_recordOptions", "lp_acorn_Acorn_Features_TemporalDecision_own", "lp_acorn_Acorn_Handcrafted_PredictionControl_advanceWith", "lp_acorn_Acorn_Handcrafted_FeatureProfile_usesHierarchy", "lp_acorn_Acorn_Handcrafted_askQuestions"]),
  ("Handcrafted/PredictionControl", "lp_acorn_Acorn_Handcrafted_PredictionControl_advance", #["lp_acorn_Acorn_Handcrafted_evaluateCumulants", "lp_acorn_Acorn_Handcrafted_PredictionControl_advanceWith"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_askQuestions", #["lp_acorn___private_Init_Data_Array_Basic_0__Array_mapFinIdxMUnsafe_map___at___00Acorn_Handcrafted_askQuestions_spec__0___redArg"]),
  ("Handcrafted/TemporalControl", "lp_acorn___private_Init_Data_Array_Basic_0__Array_mapFinIdxMUnsafe_map___at___00Acorn_Handcrafted_askQuestions_spec__0___redArg", #["lp_acorn_Acorn_Handcrafted_askedBy", "lp_acorn_Acorn_Features_OptionQuestions_follow___redArg"]),
  ("OffPolicy", "lp_acorn_Acorn_Features_OptionQuestions_follow___redArg", #["lp_acorn_Acorn_Features_Preceding_advance___redArg", "lp_acorn_Acorn_Features_GradientBank_step___redArg"]),
  ("OffPolicy", "lp_acorn_Acorn_Features_Preceding_advance___redArg", #["lp_acorn_List_filterTR_loop___at___00Acorn_Features_Preceding_advance_spec__0", "lp_acorn_List_filterTR_loop___at___00Acorn_Features_Preceding_advance_spec__1", "lp_acorn_List_foldl___at___00Acorn_Features_setFlags_spec__0___redArg", "lp_acorn_List_foldl___at___00Acorn_Features_setFlags_spec__0___redArg", "lp_acorn_List_filterTR_loop___at___00Acorn_Features_Preceding_advance_spec__1", "lp_acorn_Acorn_Features_gradientStep", "lp_acorn_Acorn_Binary64_mul"]),
  ("OffPolicy", "lp_acorn_Acorn_Features_gradientStep", #["lp_acorn_Acorn_Features_wideCount", "lp_acorn_Acorn_Binary64_div", "lp_acorn_Acorn_Binary64_less"]),
  ("OffPolicy", "lp_acorn_Acorn_Features_GradientBank_step___redArg", #["lp_acorn_Acorn_Features_Question_step___redArg", "lp_acorn_Acorn_Features_GradientBank_step___redArg"]),
  ("OffPolicy", "lp_acorn_Acorn_Features_Question_step___redArg", #["lp_acorn_Acorn_Features_GradientLearner_step___redArg"]),
  ("OffPolicy", "lp_acorn_Acorn_Features_GradientLearner_initial", #["lean_mk_array", "l_Array_ofFn___redArg"]),
  ("OffPolicy", "lp_acorn_Acorn_Features_GradientLearner_step___redArg", #["lp_acorn_Acorn_Features_GradientLearner_increments___redArg", "lp_acorn_List_foldl___at___00Acorn_Features_addAll_spec__0___redArg", "lp_acorn_List_foldl___at___00Acorn_Features_addAll_spec__0___redArg", "lp_acorn_List_foldl___at___00Acorn_Features_subAll_spec__0___redArg", "lp_acorn_List_foldl___at___00Acorn_Features_addAll_spec__0___redArg"]),
  ("OffPolicy", "lp_acorn_Acorn_Features_GradientLearner_increments___redArg", #["lp_acorn_Acorn_Features_GradientLearner_scalars___redArg", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Conversion_narrow", "lp_acorn_Acorn_Conversion_narrow", "lp_acorn_Acorn_Binary64_sub", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Conversion_narrow", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Conversion_narrow"]),
  ("OffPolicy", "lp_acorn_Acorn_Features_GradientLearner_scalars___redArg", #["lp_acorn_Acorn_Discount_gamma", "lp_acorn_Acorn_Conversion_widen", "lp_acorn_Acorn_Binary64_sub", "lp_acorn_List_foldl___at___00Acorn_Features_wideSum_spec__0___redArg", "lp_acorn_List_foldl___at___00Acorn_Features_wideSum_spec__0___redArg", "lp_acorn_List_foldl___at___00Acorn_Features_wideSum_spec__0___redArg", "lp_acorn_List_foldl___at___00Acorn_Features_wideSum_spec__0___redArg", "lp_acorn_Acorn_Conversion_widen", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_add", "lp_acorn_Acorn_Binary64_sub", "lp_acorn_Acorn_Binary64_sub", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_add", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_add", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_add", "lp_acorn_Acorn_Binary64_sub", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_mul", "lp_acorn_Acorn_Binary64_sub"]),
  ("OffPolicy", "lp_acorn_List_foldl___at___00Acorn_Features_wideSum_spec__0___redArg", #["lp_acorn_Acorn_Conversion_widen", "lp_acorn_Acorn_Binary64_add"]),
  ("OffPolicy", "lp_acorn_List_foldl___at___00Acorn_Features_addAll_spec__0___redArg", #["lp_acorn_Acorn_Binary32_add", "lp_acorn_Acorn_Weight_project"]),
  ("OffPolicy", "lp_acorn_List_foldl___at___00Acorn_Features_subAll_spec__0___redArg", #["lp_acorn_Acorn_Binary32_sub", "lp_acorn_Acorn_Weight_project"]),
  ("TemporalDriver", "lp_acorn_Acorn_TemporalDriver_execute", #["lp_acorn_Acorn_Features_Skill_beginTemporal___redArg", "lp_acorn_Acorn_Features_Skill_stepTemporal___redArg", "lp_acorn_Acorn_Features_Skill_decideOption___redArg", "lp_acorn_Acorn_Features_Skill_endTemporal___redArg", "lp_acorn_Acorn_Features_PolicySnapshot_drawPersistent", "lp_acorn_Acorn_Features_planningBoundary"]),
  ("Models", "lp_acorn_Acorn_Features_Model_begin", #["lp_acorn_Acorn_Features_modelInput", "lp_acorn_Acorn_Features_Managed_apply___redArg"]),
  ("Models", "lp_acorn_Acorn_Features_Model_step", #["lp_acorn_Acorn_Features_modelInput", "lp_acorn_Acorn_Features_Managed_apply___redArg"]),
  ("Models", "lp_acorn_Acorn_Features_Model_terminal___redArg", #["lp_acorn_Acorn_Features_Transition_outcome", "lp_acorn_Acorn_Features_Managed_apply___redArg", "lp_acorn_Acorn_Features_Transition_terminal"]),
  ("Planning", "lp_acorn_Acorn_Features_Controller_plan___redArg", #["lp_acorn_Acorn_NumericState_planStep___redArg"]),
  ("Planning", "lp_acorn_Acorn_Features_PlanningResult_lookAhead___redArg", #["lp_acorn_Acorn_Features_Model_predict", "lp_acorn_Acorn_Features_metaOfSkill", "lp_acorn_Acorn_Features_ModelPrediction_target", "lp_acorn_Acorn_Features_Controller_plan___redArg", "lp_acorn_Acorn_Features_ModelPrediction_cache___redArg"]),
  ("Planning", "lp_acorn_Acorn_Features_PlanningResult_backup___redArg", #["lp_acorn_Acorn_Features_PlanningResult_lookAhead___redArg"]),
  ("Planning", "lp_acorn_Acorn_Features_PlanningResult_sweep___redArg", #["lp_acorn_Acorn_Features_PlanningResult_lookAhead___redArg"]),
  ("Planning", "lp_acorn_List_foldl___at___00Acorn_Features_PlanningResult_backupAll_spec__0___redArg", #["lp_acorn_Acorn_Features_PlanningResult_backup___redArg"]),
  ("Planning", "lp_acorn_List_foldl___at___00Acorn_Features_PlanningResult_sweepAll_spec__0___redArg", #["lp_acorn_Acorn_Features_PlanningResult_sweep___redArg"]),
  ("Planning", "lp_acorn_Acorn_Features_planningBoundary", #["lp_acorn_Acorn_Features_PlanningResult_backupAll", "lp_acorn_Acorn_Features_RecentFeatures_selected___redArg", "lp_acorn_Acorn_Features_PlanningResult_sweepAll", "lp_acorn_Acorn_Features_planningClock", "lp_acorn_Acorn_Features_RecentFeatures_advance___redArg"]),
  ("Models", "lp_acorn_Acorn_Features_Model_predict", #["lp_acorn_Acorn_Features_modelInput", "lp_acorn_Acorn_NumericState_linearPrediction___redArg", "lp_acorn_Acorn_Features_Transition_lookahead", "lp_acorn_Acorn_Features_Criterion_modelContinuation"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_lookahead", #["lp_acorn_Acorn_Features_Transition_outcomeValues", "lp_acorn_Acorn_Features_comparisonValue"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_outcomeValues", #["lp_acorn_Acorn_Features_RankedFeatures_input", "lp_acorn_Acorn_Features_Transition_expectedAt", "lp_acorn_Acorn_Features_ValueFunction_rankedValues", "lp_acorn_Acorn_Conversion_widen"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_outcomeValues___lam__0", #["lp_acorn_Acorn_Conversion_widen", "lp_acorn_Acorn_Binary64_add", "lp_acorn_Acorn_NumericState_linearPrediction___redArg", "lp_acorn_Acorn_Conversion_widen", "lp_acorn_Acorn_Binary64_add", "lp_acorn_Acorn_Conversion_narrow"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_outcome", #["lp_acorn_Acorn_Features_RankedFeatures_indicator", "lp_acorn_Acorn_Features_Controller_predictAll___redArg", "lp_acorn_Acorn_Features_ValueFunction_rankedValues", "lp_acorn_Acorn_Features_comparisonValue", "lp_acorn_Acorn_Binary32_sub", "lp_acorn_Acorn_ValueRule_gamma", "lp_acorn_Acorn_Binary32_mul"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_outcome___lam__0", #["lp_acorn_Acorn_Binary32_sub", "lp_acorn_Acorn_Binary32_mul"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_expected", #["lp_acorn_Acorn_Features_RankedFeatures_input", "lp_acorn_Acorn_Features_Transition_expectedAt"]),
  ("Models", "lp_acorn_Acorn_Features_ValueFunction_rankedNominal", #["lp_acorn_Acorn_Features_ValueFunction_rankedValues", "lp_acorn_Acorn_Features_comparisonValue"]),
  ("Models", "lp_acorn_Acorn_Features_ValueFunction_rankedValues", #["lp_acorn_Acorn_Features_RankedFeatures_occupied"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_residual", #["lp_acorn_Acorn_Features_ValueFunction_nominal", "lp_acorn_Acorn_Features_RankedFeatures_indicator", "lp_acorn_Acorn_Features_ValueFunction_rankedNominal", "lp_acorn_Acorn_Binary32_sub"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_residualTarget", #["lp_acorn_Acorn_ValueRule_gamma", "lp_acorn_Acorn_Features_Transition_residual", "lp_acorn_Acorn_Binary32_mul"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_begin", #["lp_acorn_Acorn_Features_RankedFeatures_input", "lp_acorn_Acorn_Features_Transition_updateRows___redArg"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_terminal", #["lp_acorn_Acorn_Features_Transition_updateRows___redArg"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_stop", #["lp_acorn_Acorn_Features_Transition_updateRows___redArg"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_terminal___lam__1", #["lp_acorn_Acorn_Binary32_mul", "lp_acorn_Acorn_Features_Managed_apply___redArg"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_stop___lam__1", #["lp_acorn_Acorn_Binary32_mul", "lp_acorn_Acorn_Features_Managed_stopTrajectory"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_terminal___lam__0", #["lp_acorn_Acorn_Features_Managed_apply___redArg"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_stop___lam__0", #["lp_acorn_Acorn_Features_Managed_stopTrajectory"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_step___lam__0", #["lp_acorn_Acorn_Features_Managed_apply___redArg"]),
  ("Models", "lp_acorn_Acorn_Features_Transition_restart___lam__0", #["lp_acorn_Acorn_Features_Managed_restartTrajectory"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_select", #["lp_acorn_Acorn_Features_modelOperations", "lp_acorn_Acorn_Handcrafted_TemporalControl_selectWithOperations"]),
  ("AgentDriver", "lp_acorn_Acorn_AgentDriver_execute", #["lp_acorn_Acorn_Handcrafted_AgentConstruction_execute", "lp_acorn_Acorn_Handcrafted_Agent_observe___redArg"]),
  ("Host/AgentAdmission", "lp_acorn_Acorn_Handcrafted_AgentConstruction_execute", #["lp_acorn_Acorn_Handcrafted_AgentConstruction_initial", "lp_acorn_Acorn_Handcrafted_Agent_runPrefix"]),
  ("Handcrafted/Agent", "lp_acorn_Acorn_Handcrafted_Agent_act", #["lp_acorn_Acorn_Handcrafted_Agent_advanceClock___redArg", "lp_acorn_Acorn_Handcrafted_Agent_frame___redArg", "lp_acorn_Acorn_Handcrafted_TemporalControl_alignedStep___redArg", "lp_acorn_Acorn_Handcrafted_Agent_retire___redArg"]),
  ("Host/AgentPrefix", "lp_acorn_Acorn_Handcrafted_Agent_runPrefix", #["lp_acorn_Acorn_Handcrafted_Agent_input"]),
  ("Host/Checkpoint/Frame", "lp_acorn_Acorn_Checkpoint_encode", #["lp_acorn_Acorn_Checkpoint_payloadCodec", "lp_acorn_Acorn_Rng_fnv"]),
  ("Host/Checkpoint/Frame", "lp_acorn_Acorn_Checkpoint_decode", #["lp_acorn_Acorn_Checkpoint_payloadCodec", "lp_acorn_Acorn_Rng_fnv"]),
  ("Host/Checkpoint/Admission", "lp_acorn_Acorn_Checkpoint_loadCandidate", #["lp_acorn_Acorn_Checkpoint_admitHeader", "lp_acorn_Acorn_Checkpoint_decode", "lp_acorn_Acorn_Checkpoint_admitPayload"]),
  ("Host/Checkpoint/Admission", "lp_acorn_Acorn_Checkpoint_admitPayload", #["lp_acorn_Acorn_Checkpoint_admitHeader", "lp_acorn_Acorn_Features_FeatureImage_admit___redArg", "lp_acorn_Acorn_Checkpoint_admitLifetime"]),
  ("Host/Checkpoint/Admission", "lp_acorn_Acorn_Checkpoint_load", #["lp_acorn_Acorn_Checkpoint_loadCandidate", "lp_acorn_Acorn_Handcrafted_Agent_restore___redArg"]),
  ("Host/Checkpoint/Snapshot", "lp_acorn_Acorn_Checkpoint_saveBytes", #["lp_acorn_Acorn_Handcrafted_FeatureProfile_checkpointSupported", "lp_acorn_Acorn_Checkpoint_snapshot", "lp_acorn_Acorn_Checkpoint_encode"]),
  ("Host/Checkpoint/IO", "lp_acorn_Acorn_Checkpoint_loadFile", #["lp_acorn_Acorn_Checkpoint_readBounded", "lp_acorn_Acorn_Checkpoint_load"]),
  ("Host/Checkpoint/IO", "lp_acorn_Acorn_Checkpoint_Store_save", #["lp_acorn_Acorn_Checkpoint_saveBytes", "lp_acorn___private_Acorn_Host_Checkpoint_IO_0__Acorn_Checkpoint_Store_reserve", "lp_acorn___private_Acorn_Host_Checkpoint_IO_0__Acorn_Checkpoint_Temporary_write", "lp_acorn___private_Acorn_Host_Checkpoint_IO_0__Acorn_Checkpoint_Temporary_flush", "lp_acorn___private_Acorn_Host_Checkpoint_IO_0__Acorn_Checkpoint_Temporary_sync", "lp_acorn___private_Acorn_Host_Checkpoint_IO_0__Acorn_Checkpoint_Temporary_publish"]),
  ("WorldDriver", "lp_acorn_Acorn_WorldDriver_execute", #["lp_acorn_Acorn_Host_WorldConfig_standard", "lp_acorn_Acorn_Host_World_initial", "lp_acorn_Acorn_Host_World_advanceActions", "lp_acorn_Acorn_Host_World_observe"]),
  ("Host/WorldGeneration", "lp_acorn_Acorn_Host_World_initial", #["lp_acorn_Acorn_Host_World_empty", "lp_acorn_Acorn_Host_selectSpawn", "lp_acorn_Acorn_Host_initializeDeer"]),
  ("Host/WorldDynamics", "lp_acorn_Acorn_Host_World_step", #["lp_acorn_Acorn_Host_payAndAct", "lp_acorn_Acorn_Host_World_applyActive___redArg", "lp_acorn_Acorn_Host_passiveChange", "lp_acorn_Acorn_Host_World_applyPassive___redArg", "lp_acorn_Acorn_Host_World_goalSatisfied___redArg"]),
  ("Host/Terrain", "lp_acorn_Acorn_Host_valueNoise", #["lp_acorn_Acorn_Host_coordinateFloat", "lp_acorn_Acorn_Binary32_div", "lp_acorn_Acorn_Host_floor32", "lp_acorn_Acorn_Binary32_sub", "lp_acorn_Acorn_Host_coordinateCast", "lp_acorn_Acorn_Host_Coordinate_checked"]),
  ("Host/Attempt", "lp_acorn_Acorn_Host_PreparedStep_commit___redArg", #["lp_acorn_Acorn_Host_PreparedStep_environment___redArg", "lp_acorn_Acorn_Host_EnvironmentStep_record___redArg"]),
  ("Host/Attempt", "lp_acorn_Acorn_Host_PreparedStep_environment___redArg", #["lp_acorn_Acorn_Host_World_step"]),
  ("Host/Attempt", "lp_acorn_Acorn_Host_EnvironmentStep_record___redArg", #["lp_acorn_Acorn_Host_StepResult_reward", "lp_acorn_Acorn_Host_foldAction", "lp_acorn_Acorn_Binary32_add"]),
  ("Host/Runner", "lp_acorn_Acorn_Host_runCampaign___redArg", #["lp_acorn_Acorn_Host_ResearchProfile_resumable", "lp_acorn_Acorn_Host_standardCurriculum", "lp_acorn_Acorn_Host_CampaignPlan_admit", "lp_acorn_Acorn_Host_World_initial"]),
  ("Host/Runner", "lp_acorn_Acorn_Host_runCampaign___redArg___lam__1", #["lp_acorn_Acorn_Host_WritableCheckpoint_admit"]),
  ("Host/Runner", "lp_acorn_Acorn_Host_runCampaign___redArg___lam__0", #["lp_acorn_Acorn_Host_runAdmittedCampaign___redArg"]),
  ("Host/Runner", "lp_acorn___private_Init_While_0__repeatM_erased___at___00Acorn_Host_runAdmittedCampaign_spec__0___redArg", #["lp_acorn_Acorn_Host_campaignStep___redArg"]),
  ("Host/Runner", "lp_acorn_Acorn_Host_campaignStep___redArg", #["lp_acorn_Acorn_Host_Attempt_start___redArg", "lp_acorn_Acorn_Host_runAttempt___redArg"]),
  ("Host/Attempt", "lp_acorn_Acorn_Host_DecisionInput_selectOwned___redArg", #["lean_apply_3"]),
  ("Host/Attempt", "lp_acorn_Acorn_Host_OwnedStep_frame___redArg", #["lp_acorn_Acorn_Host_captureFrame___redArg"]),
  ("Host/Attempt", "lp_acorn_Acorn_Host_OwnedStep_environment___redArg", #["lp_acorn_Acorn_Host_World_step"]),
  ("Host/Attempt", "lp_acorn_Acorn_Host_OwnedEnvironment_record___redArg", #["lp_acorn_Acorn_Host_StepResult_reward", "lean_apply_3", "lp_acorn_Acorn_Host_foldAction", "lp_acorn_Acorn_Binary32_add"]),
  ("Host/Runner", "lp_acorn_Acorn_Host_runAttempt___redArg", #["lp_acorn_Acorn_Host_runAttemptSteps___redArg"]),
  ("Host/Runner", "lp_acorn_Acorn_Host_runAttemptSteps___redArg", #["lp_acorn_Acorn_Host_Attempt_sense___redArg", "l_IO_lazyPure___redArg", "lean_alloc_closure", "lp_acorn_Acorn_Host_notifyObserver", "l_IO_lazyPure___redArg", "lp_acorn_Acorn_Host_OwnedEnvironment_record___redArg"]),
  ("Host/Runner", "lp_acorn_Acorn_Host_runAttemptSteps___redArg___lam__1", #["lp_acorn_Acorn_Host_DecisionInput_selectOwned___redArg"]),
  ("Host/Runner", "lp_acorn_Acorn_Host_runAttemptSteps___redArg___lam__2", #["lp_acorn_Acorn_Host_OwnedStep_frame___redArg"]),
  ("Host/Runner", "lp_acorn_Acorn_Host_runAttemptSteps___redArg___lam__3", #["lp_acorn_Acorn_Host_OwnedStep_environment___redArg"]),
  ("Host/Runner", "lp_acorn_Acorn_Host_StreamObserver_deliverStep___redArg", #["lean_apply_1", "lean_apply_3"]),
  ("Host/Runner", "lp_acorn_Acorn_Host_finishAttempt___redArg", #["lp_acorn_Acorn_Host_Attempt_finish___redArg", "lp_acorn_Acorn_Host_notifyObserver"])
]

/-- Ordered closure code pointers connect deferred IO and capture to the same
reviewed owners; checking a detached lambda alone does not establish that link. -/
def closures : Array (String × String × Array String) := #[
  ("Host/Runner", "lp_acorn_Acorn_Host_runAttemptSteps___redArg", #[
    "lp_acorn_Acorn_Host_runAttemptSteps___redArg___lam__1",
    "lp_acorn_Acorn_Host_runAttemptSteps___redArg___lam__2",
    "lp_acorn_Acorn_Host_StreamObserver_deliverStep___boxed",
    "lp_acorn_Acorn_Host_runAttemptSteps___redArg___lam__3"]),
  ("Sarsa", "lp_acorn_Acorn_Features_Controller_creditStep", #[
    "lp_acorn_Acorn_Features_Controller_creditStep___lam__0___boxed"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_stepOption___redArg", #[
    "lp_acorn_Acorn_Handcrafted_TemporalControl_stepOption___redArg___lam__0___boxed"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_closeOption___redArg", #[
    "lp_acorn_Acorn_Handcrafted_TemporalControl_closeOption___redArg___lam__0___boxed"]),
  ("Handcrafted/TemporalControl", "lp_acorn_Acorn_Handcrafted_TemporalControl_dispatchMeta", #[
    "lp_acorn_Acorn_Handcrafted_TemporalControl_dispatchMeta___lam__0___boxed"])
]

end AcornNativeRoutes
